import type { CheckpointStore, EventBus } from './runtime.ts';
export interface PipelineSource { id: string; universeId: string; fingerprint: string; mediaType: string; immutableRef: string }
export interface PipelineProposal { id: string; sourceId: string; kind: 'entity' | 'claim' | 'relationship' | 'event'; payload: unknown; evidenceIds: string[]; confidence: number; status: 'staged' }
export interface PipelinePorts { ingest(source: PipelineSource): Promise<{ documentIds: string[] }>; extract(universeId: string, documentIds: string[]): Promise<PipelineProposal[]>; submitReview(proposals: PipelineProposal[]): Promise<string[]>; updateWiki(universeId: string, approvedProposalIds: string[]): Promise<string[]> }
export interface ImportReport { runId: string; sourceId: string; fingerprint: string; status: 'completed' | 'skipped' | 'awaiting-review'; documentIds: string[]; proposalIds: string[]; reviewIds: string[]; updatedPageIds: string[]; startedAtUtc: string; completedAtUtc: string; checkpoints: string[] }
export class AutonomousKnowledgePipeline { #fingerprints = new Map<string, string>(); #state = new Map<string, { documentIds: string[]; proposals: PipelineProposal[]; reviewIds: string[] }>(); readonly checkpoints: CheckpointStore; readonly events: EventBus; readonly ports: PipelinePorts; constructor(checkpoints: CheckpointStore, events: EventBus, ports: PipelinePorts) { this.checkpoints = checkpoints; this.events = events; this.ports = ports; }
  async process(source: PipelineSource, approvedProposalIds: string[] = []): Promise<ImportReport> { if (!/^[a-f0-9]{64}$/.test(source.fingerprint) || !source.immutableRef) throw new Error('Invalid immutable source'); const runId = `pipeline:${source.id}:${source.fingerprint}`; const startedAtUtc = new Date().toISOString(); const checkpoints: string[] = [];
    if (this.#fingerprints.get(source.id) === source.fingerprint) {
      if (!approvedProposalIds.length) return { runId, sourceId: source.id, fingerprint: source.fingerprint, status: 'skipped', documentIds: [], proposalIds: [], reviewIds: [], updatedPageIds: [], startedAtUtc, completedAtUtc: new Date().toISOString(), checkpoints };
      const state = this.#state.get(runId); if (!state) throw new Error('Pipeline resume state missing'); const allowed = new Set(state.proposals.map((item) => item.id)); if (approvedProposalIds.some((id) => !allowed.has(id))) throw new Error('Unknown approved proposal'); const updatedPageIds = await this.ports.updateWiki(source.universeId, approvedProposalIds); this.checkpoints.save(runId, '4-wiki-updated', { updatedPageIds }); checkpoints.push('4-wiki-updated'); return { runId, sourceId: source.id, fingerprint: source.fingerprint, status: 'completed', documentIds: state.documentIds, proposalIds: state.proposals.map((item) => item.id), reviewIds: state.reviewIds, updatedPageIds, startedAtUtc, completedAtUtc: new Date().toISOString(), checkpoints };
    }
    const save = (step: string, data: unknown) => { this.checkpoints.save(runId, step, data); checkpoints.push(step); };
    const ingested = await this.ports.ingest(source); save('1-ingested', ingested); await this.events.publish({ id: crypto.randomUUID(), type: 'source.ingested', universeId: source.universeId, payload: ingested, occurredAtUtc: new Date().toISOString(), correlationId: runId, causationId: source.id });
    const proposals = await this.ports.extract(source.universeId, ingested.documentIds); if (proposals.some((item) => item.sourceId !== source.id || item.status !== 'staged' || !item.evidenceIds.length)) throw new Error('Unsafe pipeline proposal'); save('2-extracted', { proposalIds: proposals.map((item) => item.id) });
    const reviewIds = await this.ports.submitReview(proposals); save('3-review-submitted', { reviewIds }); this.#fingerprints.set(source.id, source.fingerprint); this.#state.set(runId, { documentIds: structuredClone(ingested.documentIds), proposals: structuredClone(proposals), reviewIds: structuredClone(reviewIds) });
    const allowed = new Set(proposals.map((item) => item.id)); if (approvedProposalIds.some((id) => !allowed.has(id))) throw new Error('Unknown approved proposal'); const updatedPageIds = approvedProposalIds.length ? await this.ports.updateWiki(source.universeId, approvedProposalIds) : []; if (updatedPageIds.length) save('4-wiki-updated', { updatedPageIds });
    const status = updatedPageIds.length ? 'completed' : 'awaiting-review'; const report = { runId, sourceId: source.id, fingerprint: source.fingerprint, status, documentIds: ingested.documentIds, proposalIds: proposals.map((item) => item.id), reviewIds, updatedPageIds, startedAtUtc, completedAtUtc: new Date().toISOString(), checkpoints } as ImportReport; await this.events.publish({ id: crypto.randomUUID(), type: 'pipeline.completed', universeId: source.universeId, payload: report, occurredAtUtc: report.completedAtUtc, correlationId: runId, causationId: source.id }); return report;
  }
}
