export interface DomainEvent<T = unknown> { id: string; type: string; universeId: string; payload: T; occurredAtUtc: string; correlationId: string; causationId: string | null }
export class EventBus { #handlers = new Map<string, Array<(event: DomainEvent) => Promise<void>>>(); on(type: string, handler: (event: DomainEvent) => Promise<void>): () => void { const list = this.#handlers.get(type) ?? []; list.push(handler); this.#handlers.set(type, list); return () => this.#handlers.set(type, list.filter((item) => item !== handler)); } async publish(event: DomainEvent): Promise<void> { for (const handler of [...(this.#handlers.get(event.type) ?? []), ...(this.#handlers.get('*') ?? [])]) await handler(structuredClone(event)); } }
export interface BackgroundJob<T = unknown> { id: string; type: string; universeId: string; payload: T; attempt: number; maxAttempts: number; availableAt: number; correlationId: string }
export class JobQueue { #ready: BackgroundJob[] = []; #dead: Array<{ job: BackgroundJob; error: string }> = []; enqueue(job: BackgroundJob): void { if (this.#ready.some((item) => item.id === job.id) || this.#dead.some((item) => item.job.id === job.id)) throw new Error('Duplicate job'); this.#ready.push(structuredClone(job)); } next(now = Date.now()): BackgroundJob | null { const index = this.#ready.findIndex((item) => item.availableAt <= now); if (index < 0) return null; return this.#ready.splice(index, 1)[0]; } retry(job: BackgroundJob, error: unknown, now = Date.now(), baseDelayMs = 1000): void { const updated = { ...structuredClone(job), attempt: job.attempt + 1 }; if (updated.attempt >= updated.maxAttempts) { this.#dead.push({ job: updated, error: String(error) }); return; } updated.availableAt = now + baseDelayMs * 2 ** Math.max(0, updated.attempt - 1); this.#ready.push(updated); } deadLetters() { return structuredClone(this.#dead); } }
export class TransactionalState<T> { #value: T; constructor(initial: T) { this.#value = structuredClone(initial); } read(): T { return structuredClone(this.#value); } async transaction<R>(work: (draft: T) => Promise<R>): Promise<R> { const draft = structuredClone(this.#value); const result = await work(draft); this.#value = draft; return result; } }
export class CheckpointStore { #points = new Map<string, { step: string; data: unknown; updatedAtUtc: string }>(); save(pipelineId: string, step: string, data: unknown): void { const current = this.#points.get(pipelineId); if (current && current.step.localeCompare(step, undefined, { numeric: true }) > 0) throw new Error('Checkpoint cannot move backwards'); this.#points.set(pipelineId, { step, data: structuredClone(data), updatedAtUtc: new Date().toISOString() }); } get(pipelineId: string) { const value = this.#points.get(pipelineId); return value ? structuredClone(value) : null; } }
export class CircuitBreaker { #failures = 0; #openedAt = 0; readonly threshold: number; readonly resetAfterMs: number; constructor(threshold = 3, resetAfterMs = 30_000) { this.threshold = threshold; this.resetAfterMs = resetAfterMs; } async execute<T>(operation: () => Promise<T>, now = Date.now()): Promise<T> { if (this.#openedAt && now - this.#openedAt < this.resetAfterMs) throw new Error('Circuit is open'); if (this.#openedAt) { this.#openedAt = 0; this.#failures = 0; } try { const result = await operation(); this.#failures = 0; return result; } catch (error) { if (++this.#failures >= this.threshold) this.#openedAt = now || 1; throw error; } } }
export class AgentLoopGuard { #signatures = new Map<string, number>(); readonly maximumRepeats: number; readonly maximumSteps: number; constructor(maximumRepeats = 3, maximumSteps = 50) { this.maximumRepeats = maximumRepeats; this.maximumSteps = maximumSteps; } check(step: number, signature: string): void { if (step >= this.maximumSteps) throw new Error('Agent step limit exceeded'); const count = (this.#signatures.get(signature) ?? 0) + 1; this.#signatures.set(signature, count); if (count > this.maximumRepeats) throw new Error('Agent loop detected'); } }
export class BudgetGuard { #spent = new Map<string, number>(); charge(scope: string, amount: number, limit: number): number { if (!Number.isFinite(amount) || amount < 0 || limit < 0) throw new Error('Invalid budget'); const next = (this.#spent.get(scope) ?? 0) + amount; if (next > limit) throw new Error('AI budget exceeded'); this.#spent.set(scope, next); return next; } spent(scope: string) { return this.#spent.get(scope) ?? 0; } }
export class ResourceQuota { #usage = new Map<string, number>(); consume(scope: string, units: number, maximum: number): number { if (!Number.isInteger(units) || units < 0 || !Number.isInteger(maximum) || maximum < 0) throw new Error('Invalid quota'); const next = (this.#usage.get(scope) ?? 0) + units; if (next > maximum) throw new Error('Resource quota exceeded'); this.#usage.set(scope, next); return next; } release(scope: string, units: number): void { this.#usage.set(scope, Math.max(0, (this.#usage.get(scope) ?? 0) - units)); } }
export class SlidingWindowRateLimiter { #calls = new Map<string, number[]>(); allow(key: string, maximum: number, windowMs: number, now = Date.now()): boolean { if (maximum < 1 || windowMs < 1) throw new Error('Invalid rate limit'); const calls = (this.#calls.get(key) ?? []).filter((time) => time > now - windowMs); if (calls.length >= maximum) { this.#calls.set(key, calls); return false; } calls.push(now); this.#calls.set(key, calls); return true; } }
