import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex } from '@noble/hashes/utils.js';
import type { CreativeWorkType } from '../creative-work/model.ts';

export type ResearchSourcePriority='S0'|'S1'|'S2'|'S3'|'S4'|'S5';
export interface ResearchSource {sourceId:string;title:string;sourceType:string;canonicalUrl:string;archiveUrl?:string;author?:string;publisher:string;publicationDate?:string;lastUpdated?:string;accessDate:string;accessStatus?:'verified-200'|'browser-required';language:string;officialStatus:'official'|'licensed'|'bibliographic'|'community-clue';sourcePriority:ResearchSourcePriority;copyrightStatus:'metadata-and-summary'|'public-web-article';isbn?:string;doi?:string;game?:string;expansion?:string;notes:string;fingerprint:string;status:'accepted'|'rejected';}
export interface WorkRecord {workId:string;universeId:'diablo';type:CreativeWorkType;title:string;originalTitle:string;alternateTitles:string[];authors:string[];seriesId?:string;seriesOrder?:number;description:string;originalLanguage:string;firstPublicationDate?:string;canonStatus:'official-licensed'|'official-primary';sourceIds:string[];relatedWorks:string[];isPartOf?:string;}
export interface EditionRecord {editionId:string;workId:string;publisher:string;publicationDate?:string;language:string;isbn?:string;format:string;pageCount?:number;editionStatement:string;sourceIds:string[];}
export interface VerifiedClaim {claimId:string;subjectId:string;predicate:string;value:string;sourceIds:string[];canonStatus:'CANON_CONFIRMED'|'CANON_PROBABLE';confidence:number;dateStatus:'EXACT'|'APPROXIMATE'|'RELATIVE'|'UNKNOWN';publicationRecommendation:'AUTO_PUBLISH_CANDIDATE'|'REVIEW_REQUIRED';reason:string;}

const fingerprint=(url:string)=>bytesToHex(sha256(new TextEncoder().encode(url)));
const source=(value:Omit<ResearchSource,'fingerprint'|'status'|'accessDate'>):ResearchSource=>({...value,accessDate:'2026-08-31',fingerprint:fingerprint(value.canonicalUrl),status:'accepted'});

export const sourceRegistry:ResearchSource[]=[
 source({sourceId:'src-blizzard-d2-story-so-far',title:'Diablo II: The Story So Far',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/23725427/diablo-ii-the-story-so-far',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo II: Resurrected',notes:'Kozmogónia, Sanctuary, Tristram és a Dark Wanderer hivatalos összefoglalója.'}),
 source({sourceId:'src-blizzard-immortal-story-so-far',title:'Diablo Immortal: The Story So Far',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/23805084/diablo-immortal-the-story-so-far',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo Immortal',notes:'Az Immortal hivatalosan a Lord of Destruction és a Diablo III közé kerül.'}),
 source({sourceId:'src-blizzard-immortal-overview',title:'Diablo Immortal Gameplay Overview',sourceType:'officialGameOverview',canonicalUrl:'https://news.blizzard.com/en-us/article/23557147/diablo-immortal-gameplay-overview-everything-you-need-to-know',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo Immortal',notes:'Öt évvel a Worldstone pusztulása utáni kezdést rögzíti.'}),
 source({sourceId:'src-blizzard-necromancer-lore',title:'Deadly Roots: The Lore of the Necromancer',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/20845162/deadly-roots-the-lore-of-the-necromancer',author:'Tyvalir',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo III',notes:'Rathma és a nekromanták hivatalos háttértörténete.'}),
 source({sourceId:'src-blizzard-d4-new-saga',title:'Diablo IV Inside the Game: A New Saga',sourceType:'developerPublication',canonicalUrl:'https://news.blizzard.com/en-us/article/23952501/diablo-iv-inside-the-game-a-new-saga',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Diablo IV-et a Diablo III után ötven évvel helyezi el.'}),
 source({sourceId:'src-blizzard-voh',title:'Vessel of Hatred',sourceType:'officialExpansionPage',canonicalUrl:'https://diablo4.blizzard.com/en-us/vessel-of-hatred',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Vessel of Hatred',notes:'Nahantu, Neyrelle és Mephisto történeti kiindulópontja.'}),
 source({sourceId:'src-blizzard-akarat-tale',title:'When Akarat Came to Nahantu',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/24145595/a-new-tale-when-akarat-came-to-nahantu',author:'Matthew J. Kirby',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Vessel of Hatred',notes:'Hivatalos webes történet; csak metaadat és saját összefoglaló tárolható.'}),
 source({sourceId:'src-blizzard-loh',title:'Lord of Hatred',sourceType:'officialExpansionPage',canonicalUrl:'https://diablo4.blizzard.com/lord-of-hatred',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Skovos és Mephisto hivatalos kampányoldala.'}),
 source({sourceId:'src-blizzard-reckoning',title:'Prepare for the Reckoning: Lord of Hatred Draws Near',sourceType:'officialNewsArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/24267729/prepare-for-the-reckoning-lord-of-hatred-draws-near',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Megerősíti, hogy a Season of Reckoning nem vezet be külön történetet.'}),
 source({sourceId:'src-blizzard-book-adria',title:'Book of Adria: A Diablo Bestiary Now Available',sourceType:'officialBookAnnouncement',canonicalUrl:'https://news.blizzard.com/en-us/article/22882128/book-of-adria-a-diablo-beastiary-now-available',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',notes:'A Book of Adria hivatalos kiadványbejelentése.'}),
 source({sourceId:'src-simon-book-cain',title:'Diablo III: Book of Cain',sourceType:'publisherCatalog',canonicalUrl:'https://www.simonandschuster.com/books/Diablo-III-Book-of-Cain/Deckard-Cain/9781608878024',publisher:'Simon & Schuster',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781608878024',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord és ISBN; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'}),
 source({sourceId:'src-blizzard-book-lorath',title:'Diablo: Book of Lorath',sourceType:'publisherCatalog',canonicalUrl:'https://gear.blizzard.com/products/diabbk0006-diablo-book-of-lorath',publisher:'Blizzard Entertainment',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',notes:'Hivatalos termék- és tartalomleírás.'}),
 source({sourceId:'src-google-moon-spider',title:'Diablo: Moon of the Spider',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_Moon_of_the_Spider.html?id=W-nbbItF5x8C',author:'Richard A. Knaak',publisher:'Google Books / Simon & Schuster',publicationDate:'2006-01-27',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781416531166',notes:'Bibliográfiai rekord; teljes szöveg nem került átvételre.'}),
 source({sourceId:'src-obnb-birthright',title:'Diablo: The Sin War, Book One: Birthright',sourceType:'nationalBibliography',canonicalUrl:'https://obnb.uk/p13557362-diablo-the-sin-war-book-one-birthright',author:'Richard A. Knaak',publisher:'Open British National Bibliography',publicationDate:'2006',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780743471220',accessStatus:'browser-required',notes:'Nemzeti bibliográfiai rekord, Pocket Star kiadás; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'}),
 source({sourceId:'src-obnb-scales-serpent',title:'Diablo: The Sin War, Book Two: Scales of the Serpent',sourceType:'nationalBibliography',canonicalUrl:'https://obnb.uk/p13678125-diablo-the-sin-war-book-2-scales-of-the-serpent',author:'Richard A. Knaak',publisher:'Open British National Bibliography',publicationDate:'2007',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780743471237',accessStatus:'browser-required',notes:'Pocket Star Books kiadás, 327 oldal.'}),
 source({sourceId:'src-obnb-knaak-bibliography',title:'Richard A. Knaak bibliográfia',sourceType:'nationalBibliography',canonicalUrl:'https://obnb.uk/a00056885-richard-a-knaak',author:'Richard A. Knaak',publisher:'Open British National Bibliography',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',notes:'A The Veiled Prophet 2007-es Simon & Schuster rekordját és ISBN-jét tartalmazza.'}),
 source({sourceId:'src-google-sin-war-box',title:'Diablo: The Sin War Box Set',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_The_Sin_War_Box_Set.html?id=iLWwmonlwtoC',author:'Richard A. Knaak',publisher:'Google Books / Simon & Schuster',publicationDate:'2011-11-22',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781451674019',notes:'A trilógia együttes e-könyv kiadásának rekordja.'}),
 source({sourceId:'src-blizzard-tales-1-2',title:'Diablo IV Short Stories: Witness and The Toll of Darkness and Light',sourceType:'officialWebStoryCollection',canonicalUrl:'https://news.blizzard.com/en-us/article/23964692/diablo-iv-short-stories-witness-and-the-toll-of-darkness-and-light',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Tales of Sanctuary első két történetének hivatalos oldala.'}),
 source({sourceId:'src-blizzard-sanctum-bone',title:'Sanctum of Bone',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/23972666/diablo-iv-short-story-sanctum-of-bone-by-carly-anne-west',author:'Carly Anne West',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Tales of Sanctuary harmadik történetének hivatalos oldala.'}),
 source({sourceId:'src-blizzard-teeth-plague',title:'Teeth of the Plague',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/23987085/diablo-iv-short-story-teeth-of-the-plague-by-z-brewer',author:'Z Brewer',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Tales of Sanctuary negyedik, befejező története.'}),
 source({sourceId:'src-blizzard-all-who-lie',title:'All Who Lie',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/24195755/a-new-tale-all-who-lie',author:'Matthew J. Kirby',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'Belial Sanctuaryba való visszatéréséhez kapcsolódó hivatalos történet.'}),
 source({sourceId:'src-blizzard-nightmares-wings',title:"On Nightmare's Wings",sourceType:'officialWebStoryCollection',canonicalUrl:'https://news.blizzard.com/en-us/article/24264017/new-tales-on-nightmares-wings',author:'Jonathan Maberry',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Három hivatalos, illusztrált történet Neyrelle, Adreona és Lorath főszereplésével.'})
];

export const creativeWorkRegistry:WorkRecord[]=[
 {workId:'work-book-of-cain',universeId:'diablo',type:'sourcebook',title:'Diablo III: Book of Cain',originalTitle:'Diablo III: Book of Cain',alternateTitles:['Book of Cain'],authors:['Deckard Cain','Blizzard Entertainment'],description:'Illusztrált, világon belüli történeti és lore-kompendium.',originalLanguage:'en',canonStatus:'official-licensed',sourceIds:['src-simon-book-cain'],relatedWorks:['work-book-of-adria','work-book-of-lorath']},
 {workId:'work-book-of-adria',universeId:'diablo',type:'bestiary',title:'Diablo: Book of Adria',originalTitle:'Diablo: Book of Adria',alternateTitles:['Book of Adria'],authors:['Blizzard Entertainment'],description:'Adria nézőpontjából összeállított illusztrált bestiárium.',originalLanguage:'en',canonStatus:'official-licensed',sourceIds:['src-blizzard-book-adria'],relatedWorks:['work-book-of-cain']},
 {workId:'work-book-of-lorath',universeId:'diablo',type:'sourcebook',title:'Diablo: Book of Lorath',originalTitle:'Diablo: Book of Lorath',alternateTitles:['Book of Lorath'],authors:['Matthew J. Kirby'],description:'Lorath Nahr feljegyzései Sanctuary nagy erejű relikviáiról.',originalLanguage:'en',canonStatus:'official-licensed',sourceIds:['src-blizzard-book-lorath'],relatedWorks:['work-book-of-cain']},
 {workId:'work-sin-war-birthright',universeId:'diablo',type:'novel',title:'Birthright',originalTitle:'Diablo: The Sin War, Book One: Birthright',alternateTitles:['The Sin War: Birthright'],authors:['Richard A. Knaak'],seriesId:'series-sin-war',seriesOrder:1,description:'A Sin War trilógia első regénye.',originalLanguage:'en',firstPublicationDate:'2006',canonStatus:'official-licensed',sourceIds:['src-obnb-birthright'],relatedWorks:[]},
 {workId:'work-moon-of-the-spider',universeId:'diablo',type:'novel',title:'Moon of the Spider',originalTitle:'Diablo: Moon of the Spider',alternateTitles:[],authors:['Richard A. Knaak'],description:'Zayl és Astrogha történetét feldolgozó licencelt Diablo-regény.',originalLanguage:'en',firstPublicationDate:'2006-01-27',canonStatus:'official-licensed',sourceIds:['src-google-moon-spider'],relatedWorks:[]},
 {workId:'work-when-akarat-came-to-nahantu',universeId:'diablo',type:'shortStory',title:'Amikor Akarat Nahantuba érkezett',originalTitle:'When Akarat Came to Nahantu',alternateTitles:[],authors:['Matthew J. Kirby'],description:'Hivatalos webes történet Akarat nahantui útjáról.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-akarat-tale'],relatedWorks:[]},
 {workId:'work-sin-war-scales-serpent',universeId:'diablo',type:'novel',title:'Scales of the Serpent',originalTitle:'Diablo: The Sin War, Book Two: Scales of the Serpent',alternateTitles:[],authors:['Richard A. Knaak'],seriesId:'series-sin-war',seriesOrder:2,description:'A Sin War trilógia második regénye.',originalLanguage:'en',firstPublicationDate:'2007',canonStatus:'official-licensed',sourceIds:['src-obnb-scales-serpent'],relatedWorks:['work-sin-war-birthright','work-sin-war-veiled-prophet']},
 {workId:'work-sin-war-veiled-prophet',universeId:'diablo',type:'novel',title:'The Veiled Prophet',originalTitle:'Diablo: The Sin War, Book Three: The Veiled Prophet',alternateTitles:[],authors:['Richard A. Knaak'],seriesId:'series-sin-war',seriesOrder:3,description:'A Sin War trilógia harmadik regénye.',originalLanguage:'en',firstPublicationDate:'2007',canonStatus:'official-licensed',sourceIds:['src-obnb-knaak-bibliography'],relatedWorks:['work-sin-war-birthright','work-sin-war-scales-serpent']},
 {workId:'work-sin-war-box-set',universeId:'diablo',type:'book',title:'The Sin War Box Set',originalTitle:'Diablo: The Sin War Box Set',alternateTitles:[],authors:['Richard A. Knaak'],description:'A teljes Sin War trilógiát egyesítő elektronikus gyűjtőkiadás műrekordja.',originalLanguage:'en',firstPublicationDate:'2011-11-22',canonStatus:'official-licensed',sourceIds:['src-google-sin-war-box'],relatedWorks:['work-sin-war-birthright','work-sin-war-scales-serpent','work-sin-war-veiled-prophet']},
 {workId:'work-tales-of-sanctuary',universeId:'diablo',type:'anthology',title:'Tales of Sanctuary',originalTitle:'Tales of Sanctuary',alternateTitles:[],authors:['Alma Katsu','Jonathan Maberry','Carly Anne West','Z Brewer'],description:'Négy hivatalos Diablo IV webes rövid történet gyűjteménye.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-tales-1-2','src-blizzard-sanctum-bone','src-blizzard-teeth-plague'],relatedWorks:['work-witness','work-toll-darkness-light','work-sanctum-bone','work-teeth-plague']},
 {workId:'work-witness',universeId:'diablo',type:'anthologyStory',title:'Witness',originalTitle:'Witness',alternateTitles:[],authors:['Alma Katsu'],description:'Tejal és a Hedaji rend történetéhez kapcsolódó hivatalos rövid történet.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-tales-1-2'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-toll-darkness-light',universeId:'diablo',type:'anthologyStory',title:'The Toll of Darkness and Light',originalTitle:'The Toll of Darkness and Light',alternateTitles:[],authors:['Jonathan Maberry'],description:'Klath-Ulna és egy fiatal paladin története.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-tales-1-2'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-sanctum-bone',universeId:'diablo',type:'anthologyStory',title:'Sanctum of Bone',originalTitle:'Sanctum of Bone',alternateTitles:[],authors:['Carly Anne West'],description:'Iolaynah scosgleni kutatásának hivatalos rövid története.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-sanctum-bone'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-teeth-plague',universeId:'diablo',type:'anthologyStory',title:'Teeth of the Plague',originalTitle:'Teeth of the Plague',alternateTitles:[],authors:['Z Brewer'],description:'Kirek és a pestist terjesztő patkányok története.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-teeth-plague'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-on-nightmares-wings',universeId:'diablo',type:'anthology',title:"On Nightmare's Wings",originalTitle:"On Nightmare's Wings",alternateTitles:[],authors:['Jonathan Maberry'],description:'Három illusztrált rémálomtörténet gyűjteménye.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-nightmares-wings'],relatedWorks:['work-nightmare-neyrelle','work-nightmare-adreona','work-nightmare-lorath']},
 ...['Neyrelle','Adreona','Lorath'].map(name=>({workId:`work-nightmare-${name.toLowerCase()}`,universeId:'diablo' as const,type:'anthologyStory' as const,title:`On Nightmare's Wings: ${name}`,originalTitle:`On Nightmare's Wings: ${name}`,alternateTitles:[],authors:['Jonathan Maberry'],description:`${name} rémálmához kapcsolódó hivatalos illusztrált történet.`,originalLanguage:'en',canonStatus:'official-primary' as const,sourceIds:['src-blizzard-nightmares-wings'],relatedWorks:[],isPartOf:'work-on-nightmares-wings'})),
 {workId:'work-all-who-lie',universeId:'diablo',type:'shortStory',title:'All Who Lie',originalTitle:'All Who Lie',alternateTitles:[],authors:['Matthew J. Kirby'],description:'Belial visszatérésének előzményeit bemutató hivatalos történet.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-all-who-lie'],relatedWorks:[]}
];

export const editionRegistry:EditionRecord[]=[
 {editionId:'edition-book-of-cain-en-9781608878024',workId:'work-book-of-cain',publisher:'Insight Editions / Simon & Schuster',language:'en',isbn:'9781608878024',format:'print',editionStatement:'Angol nyomtatott kiadás',sourceIds:['src-simon-book-cain']},
 {editionId:'edition-birthright-en-2006',workId:'work-sin-war-birthright',publisher:'Pocket Star',publicationDate:'2006',language:'en',isbn:'9780743471220',format:'print',pageCount:326,editionStatement:'Első angol kiadás bibliográfiai rekordja',sourceIds:['src-obnb-birthright']},
 {editionId:'edition-moon-spider-en-2006',workId:'work-moon-of-the-spider',publisher:'Simon & Schuster',publicationDate:'2006-01-27',language:'en',isbn:'9781416531166',format:'print',pageCount:336,editionStatement:'Angol nyomtatott kiadás',sourceIds:['src-google-moon-spider']},
 {editionId:'edition-scales-serpent-en-2007',workId:'work-sin-war-scales-serpent',publisher:'Pocket Star Books',publicationDate:'2007',language:'en',isbn:'9780743471237',format:'print',pageCount:327,editionStatement:'Angol nyomtatott kiadás',sourceIds:['src-obnb-scales-serpent']},
 {editionId:'edition-veiled-prophet-en-2007',workId:'work-sin-war-veiled-prophet',publisher:'Simon & Schuster',publicationDate:'2007',language:'en',isbn:'9780743471244',format:'print',editionStatement:'Angol nyomtatott kiadás bibliográfiai rekordja',sourceIds:['src-obnb-knaak-bibliography']},
 {editionId:'edition-sin-war-box-en-2011',workId:'work-sin-war-box-set',publisher:'Simon & Schuster',publicationDate:'2011-11-22',language:'en',isbn:'9781451674019',format:'ebook-collection',pageCount:784,editionStatement:'A teljes trilógia együttes angol e-könyv kiadása.',sourceIds:['src-google-sin-war-box']}
];

export const seriesRegistry=[{seriesId:'series-sin-war',title:'The Sin War',workIds:['work-sin-war-birthright','work-sin-war-scales-serpent','work-sin-war-veiled-prophet'],status:'complete-audit' as const}];
export const verifiedClaims:VerifiedClaim[]=[
 {claimId:'claim-immortal-between',subjectId:'diablo-immortal',predicate:'chronologicalPlacement',value:'Diablo II: Lord of Destruction után és Diablo III előtt',sourceIds:['src-blizzard-immortal-story-so-far'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-állítás.'},
 {claimId:'claim-immortal-five-years',subjectId:'diablo-immortal',predicate:'startsAfter',value:'Öt évvel a Worldstone pusztulása után',sourceIds:['src-blizzard-immortal-overview'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-állítás.'},
 {claimId:'claim-d4-fifty-years',subjectId:'diablo-4',predicate:'startsAfter',value:'Ötven évvel a Diablo III eseményei után',sourceIds:['src-blizzard-d4-new-saga'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Blizzard fejlesztői történeti összefoglaló.'},
 {claimId:'claim-voh-continuation',subjectId:'vessel-of-hatred',predicate:'continues',value:'A Neyrelle és Mephisto körüli Diablo IV-történetet folytatja Nahantuban',sourceIds:['src-blizzard-voh'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Hivatalos kiegészítőoldal.'},
 {claimId:'claim-reckoning-no-story',subjectId:'season-of-reckoning',predicate:'hasSeparateStory',value:'false',sourceIds:['src-blizzard-reckoning'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard kifejezetten kizárja a külön szezonális történetet.'}
 ,{claimId:'claim-tales-four-stories',subjectId:'work-tales-of-sanctuary',predicate:'hasParts',value:'Witness; The Toll of Darkness and Light; Sanctum of Bone; Teeth of the Plague',sourceIds:['src-blizzard-tales-1-2','src-blizzard-sanctum-bone','src-blizzard-teeth-plague'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A négy hivatalos Blizzard-történetoldal közvetlenül azonosítja a gyűjtemény részeit.'}
 ,{claimId:'claim-all-who-lie-belial',subjectId:'belial',predicate:'returnsTo',value:'Sanctuary',sourceIds:['src-blizzard-all-who-lie'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'REVIEW_REQUIRED',reason:'A visszatérés hivatalos, de a 184 eseményes fő kronológiában pontos elhelyezés előtt szerkesztői ellenőrzést igényel.'}
 ,{claimId:'claim-nightmares-wings-parts',subjectId:'work-on-nightmares-wings',predicate:'hasParts',value:'Neyrelle; Adreona; Lorath',sourceIds:['src-blizzard-nightmares-wings'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A hivatalos Blizzard-oldal három történetet és három főszereplőt nevez meg.'}
];

export const rejectedSourceLog=[{category:'pirated-full-text',reason:'Jogosulatlan teljes könyv; kutatási és publikációs forrásként elutasítva.'},{category:'fan-wiki-without-primary-citation',reason:'Csak kutatási nyom, bizonyítékként elutasítva.'}];
export const missingSourceList=['A 184 idővonalesemény teljes, egyenkénti primary-source auditja','További nyomtatott antológiák belső történeteinek Work-szintű feltárása','Diablo I és Diablo II kézikönyvek jogszerű, stabil hivatalos archív rekordjai','Magyar és további lokalizált kiadások Edition-szintű ellenőrzése'];

export function validateResearchRegistries(){
 const sourceIds=new Set(sourceRegistry.map(s=>s.sourceId));const workIds=new Set(creativeWorkRegistry.map(w=>w.workId));const editionIds=new Set(editionRegistry.map(e=>e.editionId));const seriesIds=new Set(seriesRegistry.map(s=>s.seriesId));const claimIds=new Set(verifiedClaims.map(c=>c.claimId));const issues:string[]=[];
 if(sourceIds.size!==sourceRegistry.length)issues.push('DUPLICATE_SOURCE_ID');if(workIds.size!==creativeWorkRegistry.length)issues.push('DUPLICATE_WORK_ID');if(editionIds.size!==editionRegistry.length)issues.push('DUPLICATE_EDITION_ID');if(seriesIds.size!==seriesRegistry.length)issues.push('DUPLICATE_SERIES_ID');if(claimIds.size!==verifiedClaims.length)issues.push('DUPLICATE_CLAIM_ID');
 const urls=new Set<string>();for(const s of sourceRegistry){if(!/^https:\/\//.test(s.canonicalUrl)||!/^[a-f0-9]{64}$/.test(s.fingerprint))issues.push(`INVALID_SOURCE:${s.sourceId}`);if(urls.has(s.canonicalUrl))issues.push(`DUPLICATE_SOURCE_URL:${s.sourceId}`);urls.add(s.canonicalUrl);}
 for(const w of creativeWorkRegistry){if(w.sourceIds.length===0||w.sourceIds.some(id=>!sourceIds.has(id)))issues.push(`BROKEN_WORK_SOURCE:${w.workId}`);if(w.relatedWorks.some(id=>!workIds.has(id)||id===w.workId))issues.push(`BROKEN_RELATED_WORK:${w.workId}`);if(w.isPartOf&&!workIds.has(w.isPartOf))issues.push(`BROKEN_PARENT:${w.workId}`);if(w.isPartOf===w.workId)issues.push(`SELF_PARENT:${w.workId}`);if(w.seriesId&&!seriesIds.has(w.seriesId))issues.push(`BROKEN_WORK_SERIES:${w.workId}`);const visited=new Set<string>();let cursor=w;while(cursor.isPartOf){if(visited.has(cursor.workId)){issues.push(`PARENT_CYCLE:${w.workId}`);break;}visited.add(cursor.workId);const parent=creativeWorkRegistry.find(item=>item.workId===cursor.isPartOf);if(!parent)break;cursor=parent;}}
 for(const series of seriesRegistry){if(new Set(series.workIds).size!==series.workIds.length||series.workIds.some(id=>!workIds.has(id)))issues.push(`BROKEN_SERIES:${series.seriesId}`);const orders=series.workIds.map(id=>creativeWorkRegistry.find(w=>w.workId===id)?.seriesOrder);if(orders.some((order,index)=>order!==index+1))issues.push(`BROKEN_SERIES_ORDER:${series.seriesId}`);}
 for(const e of editionRegistry){if(!workIds.has(e.workId)||e.sourceIds.length===0||e.sourceIds.some(id=>!sourceIds.has(id)))issues.push(`BROKEN_EDITION:${e.editionId}`);}for(const c of verifiedClaims){if(c.sourceIds.length===0||c.sourceIds.some(id=>!sourceIds.has(id))||c.confidence<0||c.confidence>1)issues.push(`CLAIM_WITHOUT_PROVENANCE:${c.claimId}`);}return issues;
}
