import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex } from '@noble/hashes/utils.js';
import type { CreativeWorkType } from '../creative-work/model.ts';

export type ResearchSourcePriority='S0'|'S1'|'S2'|'S3'|'S4'|'S5';
export interface ResearchSource {sourceId:string;title:string;sourceType:string;canonicalUrl:string;archiveUrl?:string;author?:string;publisher:string;publicationDate?:string;lastUpdated?:string;accessDate:string;accessStatus?:'verified-200'|'browser-required';language:string;officialStatus:'official'|'licensed'|'bibliographic'|'community-clue';sourcePriority:ResearchSourcePriority;copyrightStatus:'metadata-and-summary'|'public-web-article';isbn?:string;doi?:string;game?:string;expansion?:string;notes:string;fingerprint:string;status:'accepted'|'rejected';}
export interface WorkRecord {workId:string;universeId:'diablo';type:CreativeWorkType;title:string;originalTitle:string;alternateTitles:string[];authors:string[];seriesId?:string;seriesOrder?:number;description:string;originalLanguage:string;firstPublicationDate?:string;canonStatus:'official-licensed'|'official-primary'|'non-canon-reference';sourceIds:string[];relatedWorks:string[];isPartOf?:string;}
export interface EditionRecord {editionId:string;workId:string;publisher:string;publicationDate?:string;language:string;isbn?:string;format:string;pageCount?:number;editionStatement:string;sourceIds:string[];}
export interface VerifiedClaim {claimId:string;subjectId:string;predicate:string;value:string;sourceIds:string[];canonStatus:'CANON_CONFIRMED'|'CANON_PROBABLE';confidence:number;dateStatus:'EXACT'|'APPROXIMATE'|'RELATIVE'|'UNKNOWN'|'MYTHIC';publicationRecommendation:'AUTO_PUBLISH_CANDIDATE'|'REVIEW_REQUIRED';reason:string;}

const fingerprint=(url:string)=>bytesToHex(sha256(new TextEncoder().encode(url)));
const source=(value:Omit<ResearchSource,'fingerprint'|'status'|'accessDate'>):ResearchSource=>({...value,accessDate:'2026-08-31',fingerprint:fingerprint(value.canonicalUrl),status:'accepted'});

export const sourceRegistry:ResearchSource[]=[
 source({sourceId:'src-prh-lost-horadrim',title:'The Lost Horadrim (Diablo IV)',sourceType:'publisherCatalog',canonicalUrl:'https://www.penguinrandomhouse.com/books/538199/the-lost-horadrim-diablo-iv-by-matthew-j-kirby/',author:'Matthew J. Kirby',publisher:'Random House Worlds',publicationDate:'2026-04-21',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9780425284896',notes:'Hivatalos kiadói rekord; a Lord of Hatred előzményregényeként azonosítja, Skovos, Lorath és Adreona központi szerepével.'}),
 source({sourceId:'src-author-stay-awhile-book-1',title:'Stay Awhile and Listen: Book I Legendary Edition',sourceType:'authorPublication',canonicalUrl:'https://davidlcraddock.com/news/page/chronicles-craddock-2017/',author:'David L. Craddock',publisher:'DM Press',publicationDate:'2017-07-17',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780988409910',notes:'A szerző saját oldala az első könyv Legendary és Narrative kiadásairól; fejlesztéstörténeti háttérmunka, nem in-universe kánonforrás.'}),
 source({sourceId:'src-blizzard-tyrael-spotlight',title:'Tyrael Hero Spotlight',sourceType:'officialCharacterLore',canonicalUrl:'https://news.blizzard.com/en-us/article/13423479/tyrael-hero-spotlight',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',notes:'Hivatalos Blizzard-karakterösszefoglaló az Örök Konfliktusról, Tyraelről és a Worldstone elpusztításáról.'}),
 source({sourceId:'src-blizzard-malthael-nexus',title:'Malthael Enters the Nexus!',sourceType:'officialCharacterLore',canonicalUrl:'https://news.blizzard.com/en-us/article/20819590/malthael-enters-the-nexus',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',notes:'Hivatalos Blizzard-karakterösszefoglaló Malthaelről, a Worldstone-ról és Sanctuary elpusztításának szándékáról.'}),
 source({sourceId:'src-blizzard-d2-story-so-far',title:'Diablo II: The Story So Far',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/23725427/diablo-ii-the-story-so-far',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo II: Resurrected',notes:'Kozmogónia, Sanctuary, Tristram és a Dark Wanderer hivatalos összefoglalója.'}),
 source({sourceId:'src-blizzard-immortal-story-so-far',title:'Diablo Immortal: The Story So Far',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/23805084/diablo-immortal-the-story-so-far',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo Immortal',notes:'Az Immortal hivatalosan a Lord of Destruction és a Diablo III közé kerül.'}),
 source({sourceId:'src-blizzard-immortal-overview',title:'Diablo Immortal Gameplay Overview',sourceType:'officialGameOverview',canonicalUrl:'https://news.blizzard.com/en-us/article/23557147/diablo-immortal-gameplay-overview-everything-you-need-to-know',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo Immortal',notes:'Öt évvel a Worldstone pusztulása utáni kezdést rögzíti.'}),
 source({sourceId:'src-blizzard-necromancer-lore',title:'Deadly Roots: The Lore of the Necromancer',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/20845162/deadly-roots-the-lore-of-the-necromancer',author:'Tyvalir',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo III',notes:'Rathma és a nekromanták hivatalos háttértörténete.'}),
 source({sourceId:'src-blizzard-d4-new-saga',title:'Diablo IV Inside the Game: A New Saga',sourceType:'developerPublication',canonicalUrl:'https://news.blizzard.com/en-us/article/23952501/diablo-iv-inside-the-game-a-new-saga',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Diablo IV-et a Diablo III után ötven évvel helyezi el.'}),
 source({sourceId:'src-blizzard-d4-unveiled',title:'Diablo IV Unveiled',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/23189675/diablo-iv-unveiled',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Black Soulstone pusztulása és Malthael bukása utáni népességveszteséget, hatalmi vákuumot és Lilith felemelkedését rögzíti.'}),
 source({sourceId:'src-blizzard-crusade-history',title:'The History Behind the Crusade',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/13183881/the-history-behind-the-crusade',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo III',expansion:'Reaper of Souls',notes:'Akarat tanításait, a Zakarum felemelkedését, Mephisto korrupcióját és Akkhan keresztes rendjének eredetét ismerteti.'}),
 source({sourceId:'src-blizzard-voh',title:'Vessel of Hatred',sourceType:'officialExpansionPage',canonicalUrl:'https://diablo4.blizzard.com/en-us/vessel-of-hatred',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Vessel of Hatred',notes:'Nahantu, Neyrelle és Mephisto történeti kiindulópontja.'}),
 source({sourceId:'src-blizzard-akarat-tale',title:'When Akarat Came to Nahantu',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/24145595/a-new-tale-when-akarat-came-to-nahantu',author:'Matthew J. Kirby',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Vessel of Hatred',notes:'Hivatalos webes történet; csak metaadat és saját összefoglaló tárolható.'}),
 source({sourceId:'src-blizzard-loh',title:'Lord of Hatred',sourceType:'officialExpansionPage',canonicalUrl:'https://diablo4.blizzard.com/lord-of-hatred',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Skovos és Mephisto hivatalos kampányoldala.'}),
 source({sourceId:'src-blizzard-reckoning',title:'Prepare for the Reckoning: Lord of Hatred Draws Near',sourceType:'officialNewsArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/24267729/prepare-for-the-reckoning-lord-of-hatred-draws-near',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Megerősíti, hogy a Season of Reckoning nem vezet be külön történetet.'}),
 source({sourceId:'src-blizzard-book-adria',title:'Book of Adria: A Diablo Bestiary Now Available',sourceType:'officialBookAnnouncement',canonicalUrl:'https://news.blizzard.com/en-us/article/22882128/book-of-adria-a-diablo-beastiary-now-available',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',notes:'A Book of Adria hivatalos kiadványbejelentése.'}),
 source({sourceId:'src-simon-book-cain',title:'Diablo III: Book of Cain',sourceType:'publisherCatalog',canonicalUrl:'https://www.simonandschuster.com/books/Diablo-III-Book-of-Cain/Deckard-Cain/9781608878024',publisher:'Simon & Schuster',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781608878024',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord és ISBN; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'}),
 source({sourceId:'src-blizzard-book-lorath',title:'Diablo: Book of Lorath',sourceType:'publisherCatalog',canonicalUrl:'https://gear.blizzard.com/products/diabbk0006-diablo-book-of-lorath',publisher:'Blizzard Entertainment',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',notes:'Hivatalos termék- és tartalomleírás.'}),
 source({sourceId:'src-google-moon-spider',title:'Diablo: Moon of the Spider',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_Moon_of_the_Spider.html?id=W-nbbItF5x8C',author:'Richard A. Knaak',publisher:'Google Books / Simon & Schuster',publicationDate:'2006-01-27',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781416531166',notes:'Bibliográfiai rekord; teljes szöveg nem került átvételre.'}),
 source({sourceId:'src-obnb-birthright',title:'Diablo: The Sin War, Book One: Birthright',sourceType:'nationalBibliography',canonicalUrl:'https://obnb.uk/p13557362-diablo-the-sin-war-book-one-birthright',author:'Richard A. Knaak',publisher:'Open British National Bibliography',publicationDate:'2006',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780743471220',accessStatus:'browser-required',notes:'Nemzeti bibliográfiai rekord, Pocket Star kiadás; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'}),
 source({sourceId:'src-obnb-scales-serpent',title:'Diablo: The Sin War, Book Two: Scales of the Serpent',sourceType:'nationalBibliography',canonicalUrl:'https://obnb.uk/p13678125-diablo-the-sin-war-book-2-scales-of-the-serpent',author:'Richard A. Knaak',publisher:'Open British National Bibliography',publicationDate:'2007',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780743471237',accessStatus:'browser-required',notes:'Pocket Star Books kiadás, 327 oldal.'}),
 source({sourceId:'src-obnb-knaak-bibliography',title:'Richard A. Knaak bibliográfia',sourceType:'nationalBibliography',canonicalUrl:'https://obnb.uk/a00056885-richard-a-knaak',author:'Richard A. Knaak',publisher:'Open British National Bibliography',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',notes:'A The Veiled Prophet 2007-es Simon & Schuster rekordját és ISBN-jét tartalmazza.'}),
 source({sourceId:'src-google-sin-war-box',title:'Diablo: The Sin War Box Set',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_The_Sin_War_Box_Set.html?id=iLWwmonlwtoC',author:'Richard A. Knaak',publisher:'Google Books / Simon & Schuster',publicationDate:'2011-11-22',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781451674019',notes:'A trilógia együttes e-könyv kiadásának rekordja.'}),
 source({sourceId:'src-blizzard-tales-1-2',title:'Diablo IV Short Stories: Witness and The Toll of Darkness and Light',sourceType:'officialWebStoryCollection',canonicalUrl:'https://news.blizzard.com/en-us/article/23964692/diablo-iv-short-stories-witness-and-the-toll-of-darkness-and-light',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Tales of Sanctuary első két történetének hivatalos oldala.'}),
 source({sourceId:'src-blizzard-sanctum-bone',title:'Sanctum of Bone',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/23972666/diablo-iv-short-story-sanctum-of-bone-by-carly-anne-west',author:'Carly Anne West',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Tales of Sanctuary harmadik történetének hivatalos oldala.'}),
 source({sourceId:'src-blizzard-teeth-plague',title:'Teeth of the Plague',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/23987085/diablo-iv-short-story-teeth-of-the-plague-by-z-brewer',author:'Z Brewer',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'A Tales of Sanctuary negyedik, befejező története.'}),
 source({sourceId:'src-blizzard-all-who-lie',title:'All Who Lie',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/24195755/a-new-tale-all-who-lie',author:'Matthew J. Kirby',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'Belial Sanctuaryba való visszatéréséhez kapcsolódó hivatalos történet.'}),
 source({sourceId:'src-blizzard-nightmares-wings',title:"On Nightmare's Wings",sourceType:'officialWebStoryCollection',canonicalUrl:'https://news.blizzard.com/en-us/article/24264017/new-tales-on-nightmares-wings',author:'Jonathan Maberry',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Három hivatalos, illusztrált történet Neyrelle, Adreona és Lorath főszereplésével.'})
 ,source({sourceId:'src-blizzard-diablo-manual',title:'Diablo kézikönyv',sourceType:'officialGameManual',canonicalUrl:'https://ftp.blizzard.com/pub/misc/Diablo.PDF',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S0',copyrightStatus:'metadata-and-summary',accessStatus:'browser-required',game:'Diablo',notes:'A Blizzard saját kiszolgálóján megőrzött eredeti Diablo-kézikönyv; közvetlen játékforrás, teljes szövegét a wiki nem másolja át. Automatizált letöltése időszakosan nem elérhető.'})
 ,source({sourceId:'src-blizzard-diablo-2-manual',title:'Diablo II kézikönyv',sourceType:'officialGameManual',canonicalUrl:'https://download.blizzard.com/pub/misc/Diablo%20II%20Manual.pdf',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S0',copyrightStatus:'metadata-and-summary',accessStatus:'browser-required',game:'Diablo II',notes:'A Blizzard hivatalos Diablo II-kézikönyve; történeti és játékmeneti elsődleges forrás. Automatizált letöltése időszakosan nem elérhető.'})
 ,source({sourceId:'src-simon-the-order',title:'Diablo III: The Order',sourceType:'publisherCatalog',canonicalUrl:'https://www.simonandschuster.com/books/Diablo-III-The-Order/Nate-Kenyon/9781451645651',author:'Nate Kenyon',publisher:'Simon & Schuster / Pocket Books',publicationDate:'2013-02-26',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781451645651',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord, 464 oldal; több kiadási formátumot jelez. Automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-blizzard-lost-damned',title:'The Lost & the Damned',sourceType:'officialComicStory',canonicalUrl:'https://news.blizzard.com/en-us/article/24259141/a-new-tale-the-lost-the-damned',author:'Paul Tobin',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Hivatalos illusztrált Warlock-történet és motion comic.'})
 ,source({sourceId:'src-blizzard-webtoons-sanctuary',title:'Webtoons of Sanctuary',sourceType:'officialWebStoryCollection',canonicalUrl:'https://news.blizzard.com/en-us/article/24020031/devour-the-webtoons-of-sanctuary',author:'Jo Seok',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',notes:'Hat, eredetileg koreai epizódból álló hivatalos gyűjtemény; az oldal a történeteket Sanctuary elképzelt rémtörténeteiként keretezi.'})
 ,source({sourceId:'src-blizzard-light-extinguished',title:'A Light Extinguished: A Tribute',sourceType:'officialLoreArticle',canonicalUrl:'https://news.blizzard.com/en-us/article/24267731/a-light-extinguished-a-tribute',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'Spoileres, hivatalos történeti közlemény Neyrelle sorsáról; a fő idővonalban csak kiemelt spoilerjelzéssel használható.'})
 ,source({sourceId:'src-blizzard-warlock-lore',title:'Master Hell Itself with the Warlock',sourceType:'officialClassLore',canonicalUrl:'https://news.blizzard.com/en-us/article/24267728/master-hell-itself-with-the-warlock',publisher:'Blizzard Entertainment',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo IV',expansion:'Lord of Hatred',notes:'A Warlock eredetét, démonológiáját és Vizjerei kapcsolatát ismertető hivatalos osztály-lore.'})
 ,source({sourceId:'src-google-storm-light',title:'Diablo III: Storm of Light',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_III_Storm_of_Light.html?id=sQLZAAAAQBAJ',author:'Nate Kenyon',publisher:'Google Books / Simon & Schuster',publicationDate:'2014-02-04',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781476739847',notes:'Bibliográfiai rekord, 352 oldal; teljes szöveg nem került átvételre.'})
 ,source({sourceId:'src-google-order-de',title:'Diablo III – Der Orden',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_III_der_Orden.html?id=IVyzpwAACAAJ',author:'Nate Kenyon',publisher:'Google Books / Panini Books',publicationDate:'2012',language:'de',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9783833224386',notes:'A The Order német fordításának bibliográfiai rekordja; fordító: Tobias Toneguzzo, 393 oldal.'})
 ,source({sourceId:'src-titan-dawn-hatred',title:'Diablo: Dawn of Hatred képregénysorozat',sourceType:'publisherSeriesCatalog',canonicalUrl:'https://titan-comics.com/comics/2386-diablo-dawn-of-hatred/',author:'Cullen Bunn',publisher:'Titan Comics',publicationDate:'2026-04-22',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',accessStatus:'browser-required',notes:'Az 1–4. füzet hivatalos sorozatoldala, megjelenési dátumokkal és alkotói adatokkal; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-prh-dawn-hatred-collection',title:'Diablo: Dawn of Hatred gyűjtemény',sourceType:'publisherCatalog',canonicalUrl:'https://www.penguinrandomhouse.com/books/605261/diablo-dawn-of-hatred-by-written-by-cullen-bunn/',author:'Cullen Bunn',publisher:'Penguin Random House / Titan Comics',publicationDate:'2026-11-17',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781785865893',notes:'Előrendelhető, 136 oldalas gyűjtemény; az 1–4. füzetet és a 2025-ös FCBD történetet tartalmazza.'})
 ,source({sourceId:'src-google-legacy-blood',title:'Diablo: Legacy of Blood',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books?id=W447TRc7bk4C',author:'Richard A. Knaak',publisher:'Google Books / Simon & Schuster',publicationDate:'2001',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780671041557',notes:'Az első angol kiadás bibliográfiai rekordja, 368 oldal.'})
 ,source({sourceId:'src-google-legacy-blood-reissue',title:'Diablo: Legacy of Blood – Blizzard Legends',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo.html?id=qiVPMQAACAAJ',author:'Richard A. Knaak',publisher:'Google Books / Blizzard Entertainment',publicationDate:'2017-10-15',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781945683015',notes:'A Blizzard Legends újrakiadás bibliográfiai rekordja, 354 oldal; nem külön Work.'})
 ,source({sourceId:'src-google-black-road',title:'Diablo: The Black Road',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/The_Diablo_The_Black_Road.html?id=fSGE8cPJktwC',author:'Mel Odom',publisher:'Google Books / Simon & Schuster',publicationDate:'2002-04-02',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780743426916',notes:'Az angol kiadás bibliográfiai rekordja, 368 oldal.'})
 ,source({sourceId:'src-google-kingdom-shadow',title:'Diablo: The Kingdom of Shadow',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/The_Diablo_The_Kingdom_of_Shadow.html?id=AW5vzK_TMmEC',author:'Richard A. Knaak',publisher:'Google Books / Simon & Schuster',publicationDate:'2002-08-14',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780743423137',notes:'Az angol kiadás bibliográfiai rekordja, 352 oldal.'})
 ,source({sourceId:'src-google-demonsbane',title:'Diablo: Demonsbane',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_Demonsbane.html?id=gjBVrtkuCuMC',author:'Robert B. Marks',publisher:'Google Books / Simon & Schuster',publicationDate:'2000-10-31',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9780743418997',notes:'Az eredeti elektronikus kisregény bibliográfiai rekordja, 121 oldal.'})
 ,source({sourceId:'src-worldcat-diablo-archive',title:'Diablo Archive',sourceType:'libraryCatalog',canonicalUrl:'https://search.worldcat.org/title/Diablo-archive/oclc/234092112',author:'Richard A. Knaak; Mel Odom; Robert B. Marks',publisher:'WorldCat / Pocket Books',publicationDate:'2008',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781416576990',notes:'Könyvtári rekord az első Pocket Books gyűjteményes kiadáshoz; a négy alkotórészt külön azonosítja.'})
 ,source({sourceId:'src-google-legacy-blood-es',title:'Legado de Sangre',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Legado_de_Sangre.html?id=-PmWAAAACAAJ',author:'Richard A. Knaak',publisher:'Google Books / La Factoría de Ideas',publicationDate:'2004',language:'es',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9788498000528',notes:'A Legacy of Blood spanyol, második kiadású utánnyomása, 252 oldal; nem külön Work.'})
 ,source({sourceId:'src-google-book-tyrael',title:'Diablo III: Book of Tyrael',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_III_Book_of_Tyrael.html?id=kTmqzwEACAAJ',author:'Tyrael; Blizzard Entertainment',publisher:'Google Books / Insight Editions',publicationDate:'2016-10-04',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781608878031',notes:'A 164 oldalas kiadás bibliográfiai rekordja; a mű Cain írásrészleteit és Leah leveleit is kurátori keretben kezeli.'})
 ,source({sourceId:'src-simon-diablo-series',title:'Diablo könyvsorozat – Book of Tyrael',sourceType:'publisherSeriesCatalog',canonicalUrl:'https://www.simonandschuster.com/series/Diablo',publisher:'Simon & Schuster / Insight Editions',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',accessStatus:'browser-required',notes:'Hivatalos kiadói sorozatoldal, amely a Book of Tyraelt a Book of Cain társkiadványaként azonosítja.'})
 ,source({sourceId:'src-simon-au-horadric-library',title:'Diablo: Tales from the Horadric Library',sourceType:'publisherCatalog',canonicalUrl:'https://www.simonandschuster.com.au/books/Diablo-Tales-from-the-Horadric-Library/Barbara-Moore/9781803361659',publisher:'Simon & Schuster Australia / Titan Books',publicationDate:'2022-11-18',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781803361659',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord a 208 oldalas Titan Books kiadáshoz; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-cadl-horadric-library',title:'Diablo: Tales from the Horadric Library – katalógus és tartalomjegyzék',sourceType:'libraryCatalog',canonicalUrl:'https://catalog.cadl.org/Record/.b29840582',publisher:'Capital Area District Libraries / Titan Books',publicationDate:'2022',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781950366798',accessStatus:'browser-required',notes:'Könyvtári rekord hét biztosan azonosítható történettel és szerzővel; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-blizzard-heroes-rise-announcement',title:'Diablo III: Heroes Rise, Darkness Falls',sourceType:'officialBookAnnouncement',canonicalUrl:'https://worldofwarcraft.blizzard.com/en-us/news/7628986',publisher:'Blizzard Entertainment',publicationDate:'2012-11-27',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo III',notes:'A Blizzard hivatalos bejelentése megerősíti az e-könyv hét történetét: öt korábbi osztálytörténetet és két, addig kiadatlan írást.'})
 ,source({sourceId:'src-google-heroes-rise',title:'Diablo III: Heroes Rise, Darkness Falls',sourceType:'bibliographicCatalog',canonicalUrl:'https://books.google.com/books/about/Diablo_III_Heroes_Rise_Darkness_Falls.html?hl=en&id=WyZjEcZbZz0C&output=html_text',publisher:'Google Books / Simon & Schuster',publicationDate:'2012',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781416550907',accessStatus:'browser-required',notes:'A 288 oldalas gyűjtemény bibliográfiai rekordja és hét részes tartalomjegyzéke; teljes szöveg nem került átvételre. Automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-simon-heroes-rise',title:'Diablo III: Heroes Rise, Darkness Falls – kiadói rekord',sourceType:'publisherCatalog',canonicalUrl:'https://www.simonandschuster.com/books/Diablo-III-Heroes-Rise-Darkness-Falls/Blizzard-Entertainment/9781416550907',publisher:'Simon & Schuster',publicationDate:'2012-11-27',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781416550907',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-simon-morbed',title:'Diablo III: Morbed',sourceType:'publisherCatalog',canonicalUrl:'https://www.simonandschuster.com/books/Diablo-III-Morbed/Micky-Neilson/9781476789460',author:'Micky Neilson',publisher:'Simon & Schuster',publicationDate:'2014',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781476789460',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord az eredeti e-kisregényhez; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-worldcat-tales-sanctuary-comic',title:'Diablo: Tales of Sanctuary',sourceType:'libraryCatalog',canonicalUrl:'https://search.worldcat.org/de/title/Diablo%3A-Tales-of-sanctuary/oclc/48915157',author:'Dave Land',publisher:'WorldCat / Dark Horse Comics',publicationDate:'2001',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781569716823',notes:'Könyvtári rekord a Dark Horse első angol képregénykiadásához.'})
 ,source({sourceId:'src-blizzard-arreat-tales-sanctuary',title:'Diablo: Tales of Sanctuary – hivatalos bemutató',sourceType:'officialComicAnnouncement',canonicalUrl:'https://classic.battle.net/diablo2exp/merchandise/talesofsanctuary-0.shtml',publisher:'Blizzard Entertainment',publicationDate:'2001',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo II',notes:'A Blizzard klasszikus oldala három történetből álló, 64 oldalas Dark Horse képregényként mutatja be a művet.'})
 ,source({sourceId:'src-gcd-tales-sanctuary',title:'Diablo: Tales of Sanctuary – kiadási és történetjegyzék',sourceType:'comicsBibliography',canonicalUrl:'https://www.comics.org/issue/713249/',publisher:'Grand Comics Database',publicationDate:'2001-11-14',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781569716823',accessStatus:'browser-required',notes:'Bibliográfiai rekord a Rage, The Hand of Naz és Hatred’s Bride címekkel és alkotói adatokkal; a 68 oldalas katalógusadat eltér a Blizzard 64 oldalas belív-számától.'})
 ,source({sourceId:'src-dc-sword-justice',title:'Diablo: Sword of Justice',sourceType:'publisherCatalog',canonicalUrl:'https://www.dc.com/graphic-novels/diablo-2011/diablo-sword-of-justice',author:'Aaron Williams',publisher:'DC Comics',publicationDate:'2013-07-10',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',notes:'A hivatalos DC-gyűjteményoldal az ötfüzetes minisorozatot, a 120 oldalas kötetet és az alkotókat azonosítja.'})
 ,...[
  ['src-dc-diablo-1','Diablo #1','https://www.dc.com/comics/diablo-2011/diablo-1','2011-11-23'],['src-dc-diablo-2','Diablo #2','https://www.dc.com/comics/diablo-2011/diablo-2','2012-01-18'],['src-dc-diablo-3','Diablo #3','https://www.dc.com/comics/diablo-2011/diablo-3','2012-03-21'],['src-dc-diablo-4','Diablo #4','https://www.dc.com/comics/diablo-2011/diablo-4','2012-05-30'],['src-dc-diablo-5','Diablo #5','https://www.dc.com/comics/diablo-2011/diablo-5','2012-08-29']
 ].map(([sourceId,title,canonicalUrl,publicationDate])=>source({sourceId,title,sourceType:'publisherComicIssue',canonicalUrl,author:'Aaron Williams',publisher:'DC Comics',publicationDate,language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',notes:'Hivatalos DC-füzetoldal; 32 oldal, író Aaron Williams, rajzoló Joseph Lacroix.'}))
 ,source({sourceId:'src-obnb-sword-justice',title:'Diablo: Sword of Justice – bibliográfiai rekord',sourceType:'nationalBibliography',canonicalUrl:'https://obnb.uk/p16448914-diablo-sword-of-justice',author:'Aaron Williams',publisher:'Open British National Bibliography / DC Comics',publicationDate:'2013',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781401244972',accessStatus:'browser-required',notes:'Nemzeti bibliográfiai rekord; megerősíti, hogy a kötet a Diablo #1–5 füzeteket gyűjti össze.'})
 ,source({sourceId:'src-titan-bul-kathos',title:'Diablo: Legends of the Barbarian – Bul-Kathos',sourceType:'publisherCatalog',canonicalUrl:'https://titanbooks.com/71625-diablo-legends-of-the-barbarian-bul-kathos/',author:'John Arcudi',publisher:'Titan Books',publicationDate:'2023-07-11',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781803366135',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord a 80 oldalas, Geraldo Borges által rajzolt keménytáblás képregényhez; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-titan-rathma',title:'Diablo: Legends of the Necromancer – Rathma',sourceType:'publisherCatalog',canonicalUrl:'https://titanbooks.com/72125-diablo-legends-of-the-necromancer-rathma/',author:'Fred Kennedy',publisher:'Titan Books',publicationDate:'2024-07-23',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781835410158',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord a 80 oldalas, Adam Gorham által rajzolt keménytáblás képregényhez; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-titan-shadows-sanctuary',title:'Diablo: The Shadows of Sanctuary',sourceType:'publisherCatalog',canonicalUrl:'https://titanbooks.com/72663-diablo-the-shadows-of-sanctuary-short-story-collection/',publisher:'Titan Books',publicationDate:'2025-03-18',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781835414415',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord az ötszerzős, 272 oldalas rövidtörténet-gyűjteményhez; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-simon-au-shadows-sanctuary',title:'Diablo: The Shadows of Sanctuary – kiadói rekord',sourceType:'publisherCatalog',canonicalUrl:'https://www.simonandschuster.com.au/books/Diablo-The-Shadows-of-Sanctuary-%28Short-Story-Collection%29/Alma-Katsu/9781835414415',publisher:'Simon & Schuster Australia / Titan Books',publicationDate:'2025-03-18',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781835414415',accessStatus:'browser-required',notes:'Független hivatalos terjesztői rekord; megerősíti az öt szerzőt, a 272 oldalt és az ISBN-t.'})
 ,source({sourceId:'src-blizzard-instincts',title:'Instincts – Blood Knight short story',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/23967323/introducing-the-newest-diablo-immortal-class-blood-knight',author:'Ryan Quinn',publisher:'Blizzard Entertainment',publicationDate:'2023-07',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo Immortal',notes:'A Blizzard hivatalos Blood Knight-oldala az Instincts történetet, szerzőjét és Alodie kiinduló helyzetét azonosítja.'})
 ,source({sourceId:'src-blizzard-we-are-all-guilty',title:'We Are All Guilty – Tempest short story',sourceType:'officialWebStory',canonicalUrl:'https://news.blizzard.com/en-us/article/24096022/wield-the-fury-of-wind-and-wave-with-the-tempest',author:'Ryan Quinn',publisher:'Blizzard Entertainment',publicationDate:'2024-05',language:'en',officialStatus:'official',sourcePriority:'S1',copyrightStatus:'public-web-article',game:'Diablo Immortal',notes:'A Blizzard hivatalos Tempest-oldala a We Are All Guilty történetet, szerzőjét és Kez kiinduló helyzetét azonosítja.'})
 ,source({sourceId:'src-titan-book-prava',title:'Diablo: Book of Prava',sourceType:'publisherCatalog',canonicalUrl:'https://titanbooks.com/71935-diablo-book-of-prava/',author:'Matthew J. Kirby',publisher:'Titan Books',publicationDate:'2024-11-06',language:'en',officialStatus:'licensed',sourcePriority:'S2',copyrightStatus:'metadata-and-summary',isbn:'9781803368597',accessStatus:'browser-required',notes:'Hivatalos kiadói rekord a 160 oldalas Titan Books karakterkötethez; automatizált lekéréskor hozzáférés-védelmet alkalmaz.'})
 ,source({sourceId:'src-target-book-prava-us',title:'Diablo: Book of Prava – Blizzard-kiadás',sourceType:'retailerBibliography',canonicalUrl:'https://www.target.com/p/-/A-90932406',author:'Matthew J. Kirby',publisher:'Target / Blizzard Entertainment',publicationDate:'2024-11-19',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781956916522',accessStatus:'verified-200',notes:'Kereskedői bibliográfiai rekord a 160 oldalas Blizzard Entertainment amerikai kiadáshoz.'})
 ,source({sourceId:'src-target-bul-kathos-us',title:'Diablo: Legends of the Barbarian – Bul-Kathos, Blizzard-kiadás',sourceType:'retailerBibliography',canonicalUrl:'https://www.target.com/p/-/A-87154869',author:'John Arcudi',publisher:'Target / Blizzard Entertainment',publicationDate:'2023-07-11',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781950366965',accessStatus:'verified-200',notes:'Kereskedői bibliográfiai rekord a 80 oldalas Blizzard Entertainment amerikai kiadáshoz.'})
 ,source({sourceId:'src-target-rathma-us',title:'Diablo: Legends of the Necromancer – Rathma, Blizzard-kiadás',sourceType:'retailerBibliography',canonicalUrl:'https://www.target.com/p/-/A-89561215',author:'Fred Kennedy',publisher:'Target / Blizzard Entertainment',publicationDate:'2024-07-16',language:'en',officialStatus:'bibliographic',sourcePriority:'S3',copyrightStatus:'metadata-and-summary',isbn:'9781956916270',accessStatus:'verified-200',notes:'Kereskedői bibliográfiai rekord a 80 oldalas Blizzard Entertainment amerikai kiadáshoz.'})
];

export const creativeWorkRegistry:WorkRecord[]=[
 {workId:'work-lost-horadrim',universeId:'diablo',type:'novel',title:'The Lost Horadrim',originalTitle:'The Lost Horadrim (Diablo IV)',alternateTitles:['Az elveszett Horadrim'],authors:['Matthew J. Kirby'],description:'A Horadrim Skovosra vezető expedícióját, Lorath és Adreona szövetségét bemutató hivatalos Lord of Hatred-előzményregény.',originalLanguage:'en',firstPublicationDate:'2026-04-21',canonStatus:'official-licensed',sourceIds:['src-prh-lost-horadrim'],relatedWorks:['work-book-of-lorath']},
 {workId:'work-stay-awhile-listen-1',universeId:'diablo',type:'book',title:'Stay Awhile and Listen: Book I',originalTitle:'Stay Awhile and Listen: Book I Legendary Edition: How Two Blizzards Unleashed Diablo and Forged an Empire',alternateTitles:[],authors:['David L. Craddock'],description:'A Blizzard és az első Diablo fejlesztéstörténetét feldolgozó dokumentumkönyv; háttérforrás, nem Sanctuary kánonjának része.',originalLanguage:'en',firstPublicationDate:'2013-10-27',canonStatus:'non-canon-reference',sourceIds:['src-author-stay-awhile-book-1'],relatedWorks:[]},
 {workId:'work-book-of-cain',universeId:'diablo',type:'sourcebook',title:'Diablo III: Book of Cain',originalTitle:'Diablo III: Book of Cain',alternateTitles:['Book of Cain'],authors:['Deckard Cain','Blizzard Entertainment'],description:'Illusztrált, világon belüli történeti és lore-kompendium.',originalLanguage:'en',canonStatus:'official-licensed',sourceIds:['src-simon-book-cain'],relatedWorks:['work-book-of-adria','work-book-of-lorath']},
 {workId:'work-book-of-adria',universeId:'diablo',type:'bestiary',title:'Diablo: Book of Adria',originalTitle:'Diablo: Book of Adria',alternateTitles:['Book of Adria'],authors:['Blizzard Entertainment'],description:'Adria nézőpontjából összeállított illusztrált bestiárium.',originalLanguage:'en',canonStatus:'official-licensed',sourceIds:['src-blizzard-book-adria'],relatedWorks:['work-book-of-cain']},
 {workId:'work-book-of-lorath',universeId:'diablo',type:'sourcebook',title:'Diablo: Book of Lorath',originalTitle:'Diablo: Book of Lorath',alternateTitles:['Book of Lorath'],authors:['Matthew J. Kirby'],description:'Lorath Nahr feljegyzései Sanctuary nagy erejű relikviáiról.',originalLanguage:'en',canonStatus:'official-licensed',sourceIds:['src-blizzard-book-lorath'],relatedWorks:['work-book-of-cain']},
 {workId:'work-sin-war-birthright',universeId:'diablo',type:'novel',title:'Birthright',originalTitle:'Diablo: The Sin War, Book One: Birthright',alternateTitles:['The Sin War: Birthright'],authors:['Richard A. Knaak'],seriesId:'series-sin-war',seriesOrder:1,description:'A Sin War trilógia első regénye.',originalLanguage:'en',firstPublicationDate:'2006',canonStatus:'official-licensed',sourceIds:['src-obnb-birthright'],relatedWorks:[]},
 {workId:'work-moon-of-the-spider',universeId:'diablo',type:'novel',title:'Moon of the Spider',originalTitle:'Diablo: Moon of the Spider',alternateTitles:[],authors:['Richard A. Knaak'],description:'Zayl és Astrogha történetét feldolgozó licencelt Diablo-regény.',originalLanguage:'en',firstPublicationDate:'2006-01-27',canonStatus:'official-licensed',sourceIds:['src-google-moon-spider'],relatedWorks:[]},
 {workId:'work-when-akarat-came-to-nahantu',universeId:'diablo',type:'shortStory',title:'Amikor Akarat Nahantuba érkezett',originalTitle:'When Akarat Came to Nahantu',alternateTitles:[],authors:['Matthew J. Kirby'],description:'Hivatalos webes történet Akarat nahantui útjáról.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-akarat-tale'],relatedWorks:[]},
 {workId:'work-sin-war-scales-serpent',universeId:'diablo',type:'novel',title:'Scales of the Serpent',originalTitle:'Diablo: The Sin War, Book Two: Scales of the Serpent',alternateTitles:[],authors:['Richard A. Knaak'],seriesId:'series-sin-war',seriesOrder:2,description:'A Sin War trilógia második regénye.',originalLanguage:'en',firstPublicationDate:'2007',canonStatus:'official-licensed',sourceIds:['src-obnb-scales-serpent'],relatedWorks:['work-sin-war-birthright','work-sin-war-veiled-prophet']},
 {workId:'work-sin-war-veiled-prophet',universeId:'diablo',type:'novel',title:'The Veiled Prophet',originalTitle:'Diablo: The Sin War, Book Three: The Veiled Prophet',alternateTitles:[],authors:['Richard A. Knaak'],seriesId:'series-sin-war',seriesOrder:3,description:'A Sin War trilógia harmadik regénye.',originalLanguage:'en',firstPublicationDate:'2007',canonStatus:'official-licensed',sourceIds:['src-obnb-knaak-bibliography'],relatedWorks:['work-sin-war-birthright','work-sin-war-scales-serpent']},
 {workId:'work-sin-war-box-set',universeId:'diablo',type:'book',title:'The Sin War Box Set',originalTitle:'Diablo: The Sin War Box Set',alternateTitles:[],authors:['Richard A. Knaak'],description:'A teljes Sin War trilógiát egyesítő elektronikus gyűjtőkiadás műrekordja.',originalLanguage:'en',firstPublicationDate:'2011-11-22',canonStatus:'official-licensed',sourceIds:['src-google-sin-war-box'],relatedWorks:['work-sin-war-birthright','work-sin-war-scales-serpent','work-sin-war-veiled-prophet']},
 {workId:'work-tales-of-sanctuary',universeId:'diablo',type:'anthology',title:'Tales of Sanctuary',originalTitle:'Tales of Sanctuary',alternateTitles:[],authors:['Alma Katsu','Jonathan Maberry','Carly Anne West','Z Brewer'],description:'Négy hivatalos Diablo IV webes rövid történet gyűjteménye.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-tales-1-2','src-blizzard-sanctum-bone','src-blizzard-teeth-plague'],relatedWorks:['work-witness','work-toll-darkness-light','work-sanctum-bone','work-teeth-plague']},
 {workId:'work-witness',universeId:'diablo',type:'anthologyStory',title:'Witness',originalTitle:'Witness',alternateTitles:[],authors:['Alma Katsu'],description:'Tejal és a Hedaji rend történetéhez kapcsolódó hivatalos rövid történet.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-tales-1-2'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-toll-darkness-light',universeId:'diablo',type:'anthologyStory',title:'The Toll of Darkness and Light',originalTitle:'The Toll of Darkness and Light',alternateTitles:[],authors:['Jonathan Maberry'],description:'Klath-Ulna és egy fiatal paladin története.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-tales-1-2'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-sanctum-bone',universeId:'diablo',type:'anthologyStory',title:'Sanctum of Bone',originalTitle:'Sanctum of Bone',alternateTitles:[],authors:['Carly Anne West'],description:'Iolaynah scosgleni kutatásának hivatalos rövid története.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-sanctum-bone'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-teeth-plague',universeId:'diablo',type:'anthologyStory',title:'Teeth of the Plague',originalTitle:'Teeth of the Plague',alternateTitles:[],authors:['Z Brewer'],description:'Kirek és a pestist terjesztő patkányok története.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-teeth-plague'],relatedWorks:[],isPartOf:'work-tales-of-sanctuary'},
 {workId:'work-on-nightmares-wings',universeId:'diablo',type:'anthology',title:"On Nightmare's Wings",originalTitle:"On Nightmare's Wings",alternateTitles:[],authors:['Jonathan Maberry'],description:'Három illusztrált rémálomtörténet gyűjteménye.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-nightmares-wings'],relatedWorks:['work-nightmare-neyrelle','work-nightmare-adreona','work-nightmare-lorath']},
 ...['Neyrelle','Adreona','Lorath'].map(name=>({workId:`work-nightmare-${name.toLowerCase()}`,universeId:'diablo' as const,type:'anthologyStory' as const,title:`On Nightmare's Wings: ${name}`,originalTitle:`On Nightmare's Wings: ${name}`,alternateTitles:[],authors:['Jonathan Maberry'],description:`${name} rémálmához kapcsolódó hivatalos illusztrált történet.`,originalLanguage:'en',canonStatus:'official-primary' as const,sourceIds:['src-blizzard-nightmares-wings'],relatedWorks:[],isPartOf:'work-on-nightmares-wings'})),
 {workId:'work-all-who-lie',universeId:'diablo',type:'shortStory',title:'All Who Lie',originalTitle:'All Who Lie',alternateTitles:[],authors:['Matthew J. Kirby'],description:'Belial visszatérésének előzményeit bemutató hivatalos történet.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-all-who-lie'],relatedWorks:[]}
 ,{workId:'work-diablo-manual',universeId:'diablo',type:'manual',title:'Diablo kézikönyv',originalTitle:'Diablo Manual',alternateTitles:[],authors:['Blizzard Entertainment'],description:'Az eredeti játék hivatalos kézikönyve és közvetlen történeti forrása.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-diablo-manual'],relatedWorks:['work-diablo-2-manual']}
 ,{workId:'work-diablo-2-manual',universeId:'diablo',type:'manual',title:'Diablo II kézikönyv',originalTitle:'Diablo II Manual',alternateTitles:[],authors:['Blizzard Entertainment'],description:'A Diablo II hivatalos kézikönyve és közvetlen történeti forrása.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-diablo-2-manual'],relatedWorks:['work-diablo-manual']}
 ,{workId:'work-the-order',universeId:'diablo',type:'novel',title:'The Order',originalTitle:'Diablo III: The Order',alternateTitles:[],authors:['Nate Kenyon'],description:'Deckard Cain és a fiatal Leah történetét követő hivatalosan licencelt Diablo III-előzményregény.',originalLanguage:'en',firstPublicationDate:'2013-02-26',canonStatus:'official-licensed',sourceIds:['src-simon-the-order'],relatedWorks:[]}
 ,{workId:'work-lost-damned',universeId:'diablo',type:'comicStory',title:'The Lost & the Damned',originalTitle:'The Lost & the Damned',alternateTitles:[],authors:['Paul Tobin','Corey Peterschmidt','Christopher Mitten','Lauren Affe'],description:'A Warlock magányos és veszélyes hivatását bemutató hivatalos illusztrált történet.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-lost-damned'],relatedWorks:['work-warlock-lore']}
 ,{workId:'work-webtoons-sanctuary',universeId:'diablo',type:'anthology',title:'Webtoons of Sanctuary',originalTitle:'Webtoons of Sanctuary',alternateTitles:[],authors:['Jo Seok'],description:'Hat, eredetileg koreai webtoonból álló hivatalos rémtörténet-gyűjtemény.',originalLanguage:'ko',canonStatus:'official-primary',sourceIds:['src-blizzard-webtoons-sanctuary'],relatedWorks:['work-webtoon-goatmen','work-webtoon-new-addition','work-webtoon-cure','work-webtoon-grandfather','work-webtoon-only-darkness','work-webtoon-blood-revenant']}
 ,...['Goatmen','A New Addition','The Cure','A Visit with Grandfather','Only in Darkness','Blood for the Revenant'].map((title,index)=>({workId:['work-webtoon-goatmen','work-webtoon-new-addition','work-webtoon-cure','work-webtoon-grandfather','work-webtoon-only-darkness','work-webtoon-blood-revenant'][index],universeId:'diablo' as const,type:'comicStory' as const,title,originalTitle:title,alternateTitles:[],authors:['Jo Seok'],description:`A Webtoons of Sanctuary ${index+1}. epizódja; Sanctuary világán belül mesélt elképzelt rémtörténet.`,originalLanguage:'ko',canonStatus:'official-primary' as const,sourceIds:['src-blizzard-webtoons-sanctuary'],relatedWorks:[],isPartOf:'work-webtoons-sanctuary'}))
 ,{workId:'work-light-extinguished',universeId:'diablo',type:'newsArticle',title:'A Light Extinguished: A Tribute',originalTitle:'A Light Extinguished: A Tribute',alternateTitles:[],authors:['Blizzard Entertainment'],description:'Hivatalos, spoileres történeti közlemény Neyrelle sorsáról.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-light-extinguished'],relatedWorks:[]}
 ,{workId:'work-warlock-lore',universeId:'diablo',type:'officialWebpage',title:'A Warlock történeti háttere',originalTitle:'Master Hell Itself with the Warlock',alternateTitles:[],authors:['Blizzard Entertainment'],description:'A Warlock osztály eredetét és démonológiai hagyományát ismertető hivatalos anyag.',originalLanguage:'en',canonStatus:'official-primary',sourceIds:['src-blizzard-warlock-lore'],relatedWorks:['work-lost-damned']}
 ,{workId:'work-storm-of-light',universeId:'diablo',type:'novel',title:'Storm of Light',originalTitle:'Diablo III: Storm of Light',alternateTitles:[],authors:['Nate Kenyon'],description:'A Diablo III után, a Black Soulstone körüli válság idején játszódó licencelt regény.',originalLanguage:'en',firstPublicationDate:'2014-02-04',canonStatus:'official-licensed',sourceIds:['src-google-storm-light'],relatedWorks:['work-the-order']}
 ,{workId:'work-dawn-hatred-series',universeId:'diablo',type:'bookSeries',title:'Diablo: Dawn of Hatred',originalTitle:'Diablo: Dawn of Hatred',alternateTitles:[],authors:['Cullen Bunn','Daniele Serra'],description:'A Vessel of Hatred után játszódó négyrészes képregénysorozat.',originalLanguage:'en',firstPublicationDate:'2026-04-22',canonStatus:'official-licensed',sourceIds:['src-titan-dawn-hatred'],relatedWorks:['work-dawn-hatred-1','work-dawn-hatred-2','work-dawn-hatred-3','work-dawn-hatred-4','work-dawn-hatred-collection']}
 ,...['2026-04-22','2026-05-27','2026-06-24','2026-07-29'].map((date,index)=>({workId:`work-dawn-hatred-${index+1}`,universeId:'diablo' as const,type:'comicIssue' as const,title:`Dawn of Hatred #${index+1}`,originalTitle:`Diablo: Dawn of Hatred #${index+1}`,alternateTitles:[],authors:['Cullen Bunn','Daniele Serra'],seriesId:'series-dawn-hatred',seriesOrder:index+1,description:`A Dawn of Hatred képregénysorozat ${index+1}. füzete.`,originalLanguage:'en',firstPublicationDate:date,canonStatus:'official-licensed' as const,sourceIds:['src-titan-dawn-hatred'],relatedWorks:[],isPartOf:'work-dawn-hatred-series'}))
 ,{workId:'work-dawn-hatred-collection',universeId:'diablo',type:'graphicNovel',title:'Dawn of Hatred – gyűjtemény',originalTitle:'Diablo: Dawn of Hatred',alternateTitles:[],authors:['Cullen Bunn','Daniele Serra'],description:'Az 1–4. füzetet és a Free Comic Book Day 2025 történetet egyesítő, bejelentett gyűjtemény.',originalLanguage:'en',firstPublicationDate:'2026-11-17',canonStatus:'official-licensed',sourceIds:['src-prh-dawn-hatred-collection'],relatedWorks:['work-dawn-hatred-1','work-dawn-hatred-2','work-dawn-hatred-3','work-dawn-hatred-4']}
 ,{workId:'work-legacy-of-blood',universeId:'diablo',type:'novel',title:'Legacy of Blood',originalTitle:'Diablo: Legacy of Blood',alternateTitles:['Legado de Sangre'],authors:['Richard A. Knaak'],description:'Norrec Vizharan és Bartuc elátkozott vértezetének története.',originalLanguage:'en',firstPublicationDate:'2001',canonStatus:'official-licensed',sourceIds:['src-google-legacy-blood','src-google-legacy-blood-reissue'],relatedWorks:['work-diablo-archive']}
 ,{workId:'work-black-road',universeId:'diablo',type:'novel',title:'The Black Road',originalTitle:'Diablo: The Black Road',alternateTitles:[],authors:['Mel Odom'],description:'Darrick Lang Bramwellbe való hazatérésének és a települést behálózó sötét erőnek a története.',originalLanguage:'en',firstPublicationDate:'2002-04-02',canonStatus:'official-licensed',sourceIds:['src-google-black-road'],relatedWorks:['work-diablo-archive']}
 ,{workId:'work-kingdom-shadow',universeId:'diablo',type:'novel',title:'The Kingdom of Shadow',originalTitle:'Diablo: The Kingdom of Shadow',alternateTitles:[],authors:['Richard A. Knaak'],description:'Ureh újjászületését kutató Quov Tsin és zsoldosai története.',originalLanguage:'en',firstPublicationDate:'2002-08-14',canonStatus:'official-licensed',sourceIds:['src-google-kingdom-shadow'],relatedWorks:['work-diablo-archive','work-moon-of-the-spider']}
 ,{workId:'work-demonsbane',universeId:'diablo',type:'novella',title:'Demonsbane',originalTitle:'Diablo: Demonsbane',alternateTitles:[],authors:['Robert B. Marks'],description:'A blackmarchi mészárlást túlélő Siggard bosszúhadjáratának története.',originalLanguage:'en',firstPublicationDate:'2000-10-31',canonStatus:'official-licensed',sourceIds:['src-google-demonsbane'],relatedWorks:['work-diablo-archive']}
 ,{workId:'work-diablo-archive',universeId:'diablo',type:'anthology',title:'Diablo Archive',originalTitle:'Diablo Archive',alternateTitles:[],authors:['Richard A. Knaak','Mel Odom','Robert B. Marks'],description:'A négy korai Diablo-művet egyesítő gyűjtemény.',originalLanguage:'en',firstPublicationDate:'2008',canonStatus:'official-licensed',sourceIds:['src-worldcat-diablo-archive'],relatedWorks:['work-legacy-of-blood','work-black-road','work-kingdom-shadow','work-demonsbane']}
 ,{workId:'work-book-of-tyrael',universeId:'diablo',type:'sourcebook',title:'Diablo III: Book of Tyrael',originalTitle:'Diablo III: Book of Tyrael',alternateTitles:['Book of Tyrael'],authors:['Blizzard Entertainment'],description:'Tyrael által összeállított, illusztrált világon belüli történeti és lore-kompendium.',originalLanguage:'en',firstPublicationDate:'2016-10-04',canonStatus:'official-licensed',sourceIds:['src-google-book-tyrael','src-simon-diablo-series'],relatedWorks:['work-book-of-cain','work-book-of-adria','work-book-of-lorath']}
 ,{workId:'work-horadric-library',universeId:'diablo',type:'anthology',title:'Tales from the Horadric Library',originalTitle:'Diablo: Tales from the Horadric Library',alternateTitles:[],authors:['Matthew J. Kirby','Tamsyn Muir','Courtney Alameda','Barry Lyga','Brian Evenson','Delilah S. Dawson','Catherynne M. Valente'],description:'A Horadrim által feljegyzett helyi legendákat és sötét történeteket összegyűjtő hivatalosan licencelt antológia.',originalLanguage:'en',firstPublicationDate:'2022',canonStatus:'official-licensed',sourceIds:['src-simon-au-horadric-library','src-cadl-horadric-library'],relatedWorks:['work-gospel-death','work-rose-khanduras','work-collar-thorns','work-whiff-salt','work-tomb-tal-rasha','work-dark-seeps-in','work-beyond-door-no-light']}
 ,...[
  ['work-gospel-death','The Gospel of Death','Matthew J. Kirby'],['work-rose-khanduras','The Rose of Khanduras','Tamsyn Muir'],['work-collar-thorns','A Collar of Thorns','Courtney Alameda'],['work-whiff-salt','A Whiff of Salt','Barry Lyga'],['work-tomb-tal-rasha','The Tomb of Tal Rasha','Brian Evenson'],['work-dark-seeps-in','When the Dark Seeps In','Delilah S. Dawson'],['work-beyond-door-no-light','Beyond That Door There Lies No Light','Catherynne M. Valente']
 ].map(([workId,title,author])=>({workId,universeId:'diablo' as const,type:'anthologyStory' as const,title,originalTitle:title,alternateTitles:[],authors:[author],description:`A Tales from the Horadric Library önálló története: ${title}.`,originalLanguage:'en',canonStatus:'official-licensed' as const,sourceIds:['src-cadl-horadric-library'],relatedWorks:[],isPartOf:'work-horadric-library'}))
 ,{workId:'work-heroes-rise',universeId:'diablo',type:'anthology',title:'Heroes Rise, Darkness Falls',originalTitle:'Diablo III: Heroes Rise, Darkness Falls',alternateTitles:[],authors:['Blizzard Entertainment'],description:'Hét Diablo III-osztálytörténetet egyesítő hivatalos elektronikus antológia.',originalLanguage:'en',firstPublicationDate:'2012-11-27',canonStatus:'official-licensed',sourceIds:['src-blizzard-heroes-rise-announcement','src-google-heroes-rise','src-simon-heroes-rise'],relatedWorks:['work-hatred-discipline','work-wayfarer','work-unyielding','work-firefly','work-doubtwalker','work-theatre-macabre-dark-exile','work-hunger']}
 ,...[
  ['work-hatred-discipline','Hatred and Discipline','Micky Neilson'],['work-wayfarer','Wayfarer','Cameron Dayton'],['work-unyielding','Unyielding','Matt Burns'],['work-firefly','Firefly','Michael Chu'],['work-doubtwalker','Doubtwalker','Matt Burns'],['work-theatre-macabre-dark-exile','Theatre Macabre: The Dark Exile','James Waugh'],['work-hunger','The Hunger','Erik Sabol']
 ].map(([workId,title,author])=>({workId,universeId:'diablo' as const,type:'anthologyStory' as const,title,originalTitle:title,alternateTitles:[],authors:[author],description:`A Heroes Rise, Darkness Falls önálló osztálytörténete: ${title}.`,originalLanguage:'en',canonStatus:'official-licensed' as const,sourceIds:['src-blizzard-heroes-rise-announcement','src-google-heroes-rise'],relatedWorks:[],isPartOf:'work-heroes-rise'}))
 ,{workId:'work-morbed',universeId:'diablo',type:'novella',title:'Morbed',originalTitle:'Diablo III: Morbed',alternateTitles:[],authors:['Micky Neilson'],description:'Morbed és egy mágusból, druidából, nekromantából és keresztesből álló csoport története egy távoli szigeten.',originalLanguage:'en',firstPublicationDate:'2014',canonStatus:'official-licensed',sourceIds:['src-simon-morbed'],relatedWorks:[]}
 ,{workId:'work-tales-sanctuary-comic',universeId:'diablo',type:'graphicNovel',title:'Diablo: Tales of Sanctuary',originalTitle:'Diablo: Tales of Sanctuary',alternateTitles:[],authors:['Dave Land','Phil Amara'],description:'Három önálló történetet egyesítő Dark Horse Diablo-képregény.',originalLanguage:'en',firstPublicationDate:'2001',canonStatus:'official-licensed',sourceIds:['src-worldcat-tales-sanctuary-comic','src-blizzard-arreat-tales-sanctuary','src-gcd-tales-sanctuary'],relatedWorks:['work-tales-sanctuary-rage','work-hand-of-naz','work-hatreds-bride']}
 ,...[
  ['work-tales-sanctuary-rage','Rage','Dave Land'],['work-hand-of-naz','The Hand of Naz','Phil Amara'],['work-hatreds-bride',"Hatred's Bride",'Dave Land']
 ].map(([workId,title,author])=>({workId,universeId:'diablo' as const,type:'comicStory' as const,title,originalTitle:title,alternateTitles:[],authors:[author],description:`A Diablo: Tales of Sanctuary képregény önálló története: ${title}.`,originalLanguage:'en',canonStatus:'official-licensed' as const,sourceIds:['src-blizzard-arreat-tales-sanctuary','src-gcd-tales-sanctuary'],relatedWorks:[],isPartOf:'work-tales-sanctuary-comic'}))
 ,{workId:'work-sword-justice-series',universeId:'diablo',type:'bookSeries',title:'Diablo: Sword of Justice – minisorozat',originalTitle:'Diablo',alternateTitles:['Diablo 2011'],authors:['Aaron Williams','Joseph Lacroix'],description:'Jacob és a Sword of Justice történetét elbeszélő ötrészes DC-minisorozat.',originalLanguage:'en',firstPublicationDate:'2011-11-23',canonStatus:'official-licensed',sourceIds:['src-dc-sword-justice','src-dc-diablo-1','src-dc-diablo-2','src-dc-diablo-3','src-dc-diablo-4','src-dc-diablo-5'],relatedWorks:['work-sword-justice-1','work-sword-justice-2','work-sword-justice-3','work-sword-justice-4','work-sword-justice-5','work-sword-justice-collection']}
 ,...['2011-11-23','2012-01-18','2012-03-21','2012-05-30','2012-08-29'].map((date,index)=>({workId:`work-sword-justice-${index+1}`,universeId:'diablo' as const,type:'comicIssue' as const,title:`Diablo: Sword of Justice #${index+1}`,originalTitle:`Diablo #${index+1}`,alternateTitles:[],authors:['Aaron Williams','Joseph Lacroix'],seriesId:'series-sword-justice',seriesOrder:index+1,description:`A Sword of Justice minisorozat ${index+1}. füzete.`,originalLanguage:'en',firstPublicationDate:date,canonStatus:'official-licensed' as const,sourceIds:[`src-dc-diablo-${index+1}`],relatedWorks:[],isPartOf:'work-sword-justice-series'}))
 ,{workId:'work-sword-justice-collection',universeId:'diablo',type:'graphicNovel',title:'Diablo: Sword of Justice – gyűjtemény',originalTitle:'Diablo: Sword of Justice',alternateTitles:[],authors:['Aaron Williams','Joseph Lacroix'],description:'A Diablo #1–5 füzeteket egyesítő DC Comics-gyűjtemény.',originalLanguage:'en',firstPublicationDate:'2013-07-10',canonStatus:'official-licensed',sourceIds:['src-dc-sword-justice','src-obnb-sword-justice'],relatedWorks:['work-sword-justice-1','work-sword-justice-2','work-sword-justice-3','work-sword-justice-4','work-sword-justice-5']}
 ,{workId:'work-legends-bul-kathos',universeId:'diablo',type:'graphicNovel',title:'Legends of the Barbarian: Bul-Kathos',originalTitle:'Diablo: Legends of the Barbarian – Bul-Kathos',alternateTitles:[],authors:['John Arcudi','Geraldo Borges'],seriesId:'series-diablo-legends',seriesOrder:1,description:'Bul-Kathos, valamint ikergyermekei, Naarah és Hiram ősi történetét feldolgozó képregény.',originalLanguage:'en',firstPublicationDate:'2023-07-11',canonStatus:'official-licensed',sourceIds:['src-titan-bul-kathos','src-target-bul-kathos-us'],relatedWorks:['work-legends-rathma']}
 ,{workId:'work-legends-rathma',universeId:'diablo',type:'graphicNovel',title:'Legends of the Necromancer: Rathma',originalTitle:'Diablo: Legends of the Necromancer – Rathma',alternateTitles:[],authors:['Fred Kennedy','Adam Gorham'],seriesId:'series-diablo-legends',seriesOrder:2,description:'Linarian örökségének és a halál feletti képességei kibontakozásának története.',originalLanguage:'en',firstPublicationDate:'2024-07-16',canonStatus:'official-licensed',sourceIds:['src-titan-rathma','src-target-rathma-us'],relatedWorks:['work-legends-bul-kathos']}
 ,{workId:'work-shadows-sanctuary',universeId:'diablo',type:'anthology',title:'The Shadows of Sanctuary',originalTitle:'Diablo: The Shadows of Sanctuary',alternateTitles:[],authors:['Alma Katsu','Jonathan Maberry','Z Brewer','Ryan Quinn','Carly Anne West'],description:'Hat, korábban digitálisan megjelent Diablo IV- és Diablo Immortal-történetet egyesítő nyomtatott antológia.',originalLanguage:'en',firstPublicationDate:'2025-03-18',canonStatus:'official-licensed',sourceIds:['src-titan-shadows-sanctuary','src-simon-au-shadows-sanctuary'],relatedWorks:['work-witness','work-toll-darkness-light','work-sanctum-bone','work-teeth-plague','work-instincts','work-we-are-all-guilty']}
 ,{workId:'work-instincts',universeId:'diablo',type:'anthologyStory',title:'Instincts',originalTitle:'Instincts',alternateTitles:[],authors:['Ryan Quinn'],description:'Alodie és Linn története, amely a Blood Knight osztály bemutatásához kapcsolódik.',originalLanguage:'en',firstPublicationDate:'2023-07',canonStatus:'official-primary',sourceIds:['src-blizzard-instincts'],relatedWorks:['work-shadows-sanctuary'],isPartOf:'work-shadows-sanctuary'}
 ,{workId:'work-we-are-all-guilty',universeId:'diablo',type:'anthologyStory',title:'We Are All Guilty',originalTitle:'We Are All Guilty',alternateTitles:[],authors:['Ryan Quinn'],description:'Kez és a Tempest hagyomány története egy ködbe burkolózó hajón.',originalLanguage:'en',firstPublicationDate:'2024-05',canonStatus:'official-primary',sourceIds:['src-blizzard-we-are-all-guilty'],relatedWorks:['work-shadows-sanctuary'],isPartOf:'work-shadows-sanctuary'}
 ,{workId:'work-book-prava',universeId:'diablo',type:'sourcebook',title:'Diablo: Book of Prava',originalTitle:'Diablo: Book of Prava',alternateTitles:[],authors:['Matthew J. Kirby'],description:'Prava vallási és teológiai feljegyzéseit bemutató, illusztrált karakterkötet.',originalLanguage:'en',firstPublicationDate:'2024-11-06',canonStatus:'official-licensed',sourceIds:['src-titan-book-prava','src-target-book-prava-us'],relatedWorks:['work-book-of-cain','work-book-of-tyrael','work-book-of-adria','work-book-of-lorath']}
];

export const editionRegistry:EditionRecord[]=[
 {editionId:'edition-lost-horadrim-hardcover-en-2026',workId:'work-lost-horadrim',publisher:'Random House Worlds',publicationDate:'2026-04-21',language:'en',isbn:'9780425284896',format:'hardcover',pageCount:272,editionStatement:'Amerikai angol keménytáblás kiadás.',sourceIds:['src-prh-lost-horadrim']},
 {editionId:'edition-lost-horadrim-ebook-en-2026',workId:'work-lost-horadrim',publisher:'Random House Worlds',publicationDate:'2026-04-21',language:'en',isbn:'9780399594076',format:'ebook',pageCount:272,editionStatement:'Amerikai angol e-könyv kiadás.',sourceIds:['src-prh-lost-horadrim']},
 {editionId:'edition-stay-awhile-legendary-en-2017',workId:'work-stay-awhile-listen-1',publisher:'DM Press',publicationDate:'2017-07-17',language:'en',isbn:'9780988409910',format:'paperback',pageCount:274,editionStatement:'Legendary Edition, kiegészítő háttéranyagokkal.',sourceIds:['src-author-stay-awhile-book-1']},
 {editionId:'edition-book-of-cain-en-9781608878024',workId:'work-book-of-cain',publisher:'Insight Editions / Simon & Schuster',language:'en',isbn:'9781608878024',format:'print',editionStatement:'Angol nyomtatott kiadás',sourceIds:['src-simon-book-cain']},
 {editionId:'edition-birthright-en-2006',workId:'work-sin-war-birthright',publisher:'Pocket Star',publicationDate:'2006',language:'en',isbn:'9780743471220',format:'print',pageCount:326,editionStatement:'Első angol kiadás bibliográfiai rekordja',sourceIds:['src-obnb-birthright']},
 {editionId:'edition-moon-spider-en-2006',workId:'work-moon-of-the-spider',publisher:'Simon & Schuster',publicationDate:'2006-01-27',language:'en',isbn:'9781416531166',format:'print',pageCount:336,editionStatement:'Angol nyomtatott kiadás',sourceIds:['src-google-moon-spider']},
 {editionId:'edition-scales-serpent-en-2007',workId:'work-sin-war-scales-serpent',publisher:'Pocket Star Books',publicationDate:'2007',language:'en',isbn:'9780743471237',format:'print',pageCount:327,editionStatement:'Angol nyomtatott kiadás',sourceIds:['src-obnb-scales-serpent']},
 {editionId:'edition-veiled-prophet-en-2007',workId:'work-sin-war-veiled-prophet',publisher:'Simon & Schuster',publicationDate:'2007',language:'en',isbn:'9780743471244',format:'print',editionStatement:'Angol nyomtatott kiadás bibliográfiai rekordja',sourceIds:['src-obnb-knaak-bibliography']},
 {editionId:'edition-sin-war-box-en-2011',workId:'work-sin-war-box-set',publisher:'Simon & Schuster',publicationDate:'2011-11-22',language:'en',isbn:'9781451674019',format:'ebook-collection',pageCount:784,editionStatement:'A teljes trilógia együttes angol e-könyv kiadása.',sourceIds:['src-google-sin-war-box']}
 ,{editionId:'edition-diablo-manual-en-pdf',workId:'work-diablo-manual',publisher:'Blizzard Entertainment',language:'en',format:'official-pdf',editionStatement:'A Blizzard által megőrzött angol digitális kézikönyv.',sourceIds:['src-blizzard-diablo-manual']}
 ,{editionId:'edition-diablo-2-manual-en-pdf',workId:'work-diablo-2-manual',publisher:'Blizzard Entertainment',language:'en',format:'official-pdf',editionStatement:'A Blizzard által megőrzött angol digitális kézikönyv.',sourceIds:['src-blizzard-diablo-2-manual']}
 ,{editionId:'edition-the-order-en-2013',workId:'work-the-order',publisher:'Pocket Books',publicationDate:'2013-02-26',language:'en',isbn:'9781451645651',format:'mass-market-paperback',pageCount:464,editionStatement:'Angol tömegpiaci puhafedeles kiadás.',sourceIds:['src-simon-the-order']}
 ,{editionId:'edition-the-order-de-2012',workId:'work-the-order',publisher:'Panini Books',publicationDate:'2012',language:'de',isbn:'9783833224386',format:'print',pageCount:393,editionStatement:'Német fordítás; fordító: Tobias Toneguzzo.',sourceIds:['src-google-order-de']}
 ,{editionId:'edition-storm-light-en-2014',workId:'work-storm-of-light',publisher:'Simon & Schuster',publicationDate:'2014-02-04',language:'en',isbn:'9781476739847',format:'print',pageCount:352,editionStatement:'Angol nyomtatott kiadás bibliográfiai rekordja.',sourceIds:['src-google-storm-light']}
 ,{editionId:'edition-dawn-hatred-collection-en-2026',workId:'work-dawn-hatred-collection',publisher:'Titan Comics',publicationDate:'2026-11-17',language:'en',isbn:'9781785865893',format:'paperback',pageCount:136,editionStatement:'Bejelentett angol gyűjteményes kiadás; a hozzáférés állapota előrendelés.',sourceIds:['src-prh-dawn-hatred-collection']}
 ,{editionId:'edition-legacy-blood-en-2001',workId:'work-legacy-of-blood',publisher:'Simon & Schuster',publicationDate:'2001',language:'en',isbn:'9780671041557',format:'print',pageCount:368,editionStatement:'Első angol kiadás bibliográfiai rekordja.',sourceIds:['src-google-legacy-blood']}
 ,{editionId:'edition-legacy-blood-en-2017',workId:'work-legacy-of-blood',publisher:'Blizzard Entertainment',publicationDate:'2017-10-15',language:'en',isbn:'9781945683015',format:'print',pageCount:354,editionStatement:'Blizzard Legends angol újrakiadás.',sourceIds:['src-google-legacy-blood-reissue']}
 ,{editionId:'edition-legacy-blood-es-2004',workId:'work-legacy-of-blood',publisher:'La Factoría de Ideas',publicationDate:'2004',language:'es',isbn:'9788498000528',format:'print',pageCount:252,editionStatement:'Spanyol, második kiadású utánnyomás.',sourceIds:['src-google-legacy-blood-es']}
 ,{editionId:'edition-black-road-en-2002',workId:'work-black-road',publisher:'Simon & Schuster',publicationDate:'2002-04-02',language:'en',isbn:'9780743426916',format:'print',pageCount:368,editionStatement:'Angol nyomtatott kiadás.',sourceIds:['src-google-black-road']}
 ,{editionId:'edition-kingdom-shadow-en-2002',workId:'work-kingdom-shadow',publisher:'Simon & Schuster',publicationDate:'2002-08-14',language:'en',isbn:'9780743423137',format:'print',pageCount:352,editionStatement:'Angol nyomtatott kiadás.',sourceIds:['src-google-kingdom-shadow']}
 ,{editionId:'edition-demonsbane-en-2000',workId:'work-demonsbane',publisher:'Simon & Schuster',publicationDate:'2000-10-31',language:'en',isbn:'9780743418997',format:'ebook',pageCount:121,editionStatement:'Eredeti angol elektronikus kiadás.',sourceIds:['src-google-demonsbane']}
 ,{editionId:'edition-diablo-archive-en-2008',workId:'work-diablo-archive',publisher:'Pocket Books',publicationDate:'2008',language:'en',isbn:'9781416576990',format:'trade-paperback',editionStatement:'Első angol gyűjteményes kiadás.',sourceIds:['src-worldcat-diablo-archive']}
 ,{editionId:'edition-book-tyrael-en-2016',workId:'work-book-of-tyrael',publisher:'Insight Editions',publicationDate:'2016-10-04',language:'en',isbn:'9781608878031',format:'print',pageCount:164,editionStatement:'Angol nyomtatott kiadás bibliográfiai rekordja.',sourceIds:['src-google-book-tyrael']}
 ,{editionId:'edition-horadric-library-blizzard-en-2022',workId:'work-horadric-library',publisher:'Blizzard Entertainment',publicationDate:'2022-11-18',language:'en',isbn:'9781950366798',format:'hardcover',pageCount:196,editionStatement:'Blizzard Entertainment angol keménytáblás kiadás; a kiadási eltérés további auditot igényel.',sourceIds:['src-cadl-horadric-library']}
 ,{editionId:'edition-horadric-library-titan-en-2022',workId:'work-horadric-library',publisher:'Titan Books',publicationDate:'2022-11-18',language:'en',isbn:'9781803361659',format:'hardcover',pageCount:208,editionStatement:'Titan Books angol keménytáblás kiadás.',sourceIds:['src-simon-au-horadric-library']}
 ,{editionId:'edition-heroes-rise-en-2012',workId:'work-heroes-rise',publisher:'Simon & Schuster',publicationDate:'2012-11-27',language:'en',isbn:'9781416550907',format:'ebook-collection',pageCount:288,editionStatement:'A hét történetet egyesítő eredeti angol e-könyv.',sourceIds:['src-blizzard-heroes-rise-announcement','src-google-heroes-rise','src-simon-heroes-rise']}
 ,{editionId:'edition-morbed-en-2014',workId:'work-morbed',publisher:'Simon & Schuster',publicationDate:'2014',language:'en',isbn:'9781476789460',format:'ebook',editionStatement:'Az eredeti angol e-kisregény; a pontos napi kiadási dátum további ellenőrzésre vár.',sourceIds:['src-simon-morbed']}
 ,{editionId:'edition-tales-sanctuary-en-2001',workId:'work-tales-sanctuary-comic',publisher:'Dark Horse Comics',publicationDate:'2001-11-14',language:'en',isbn:'9781569716823',format:'graphic-novel',pageCount:64,editionStatement:'Első angol kiadás; a Blizzard 64 oldalt, a GCD borítókkal együtt 68 oldalt jelez.',sourceIds:['src-worldcat-tales-sanctuary-comic','src-blizzard-arreat-tales-sanctuary','src-gcd-tales-sanctuary']}
 ,{editionId:'edition-sword-justice-en-2013',workId:'work-sword-justice-collection',publisher:'DC Comics',publicationDate:'2013-07-10',language:'en',isbn:'9781401244972',format:'paperback',pageCount:120,editionStatement:'Az öt füzetet egyesítő angol gyűjtemény; a kiadói oldalszám elsőbbséget élvez az eltérő közösségi katalógusadattal szemben.',sourceIds:['src-dc-sword-justice','src-obnb-sword-justice']}
 ,{editionId:'edition-bul-kathos-titan-en-2023',workId:'work-legends-bul-kathos',publisher:'Titan Books',publicationDate:'2023-07-11',language:'en',isbn:'9781803366135',format:'hardcover',pageCount:80,editionStatement:'Titan Books angol keménytáblás kiadás.',sourceIds:['src-titan-bul-kathos']}
 ,{editionId:'edition-rathma-titan-en-2024',workId:'work-legends-rathma',publisher:'Titan Books',publicationDate:'2024-07-23',language:'en',isbn:'9781835410158',format:'hardcover',pageCount:80,editionStatement:'Titan Books angol keménytáblás kiadás.',sourceIds:['src-titan-rathma']}
 ,{editionId:'edition-shadows-sanctuary-titan-en-2025',workId:'work-shadows-sanctuary',publisher:'Titan Books',publicationDate:'2025-03-18',language:'en',isbn:'9781835414415',format:'hardcover',pageCount:272,editionStatement:'Titan Books angol keménytáblás antológiakiadás.',sourceIds:['src-titan-shadows-sanctuary','src-simon-au-shadows-sanctuary']}
 ,{editionId:'edition-book-prava-titan-en-2024',workId:'work-book-prava',publisher:'Titan Books',publicationDate:'2024-11-06',language:'en',isbn:'9781803368597',format:'hardcover',pageCount:160,editionStatement:'Titan Books angol keménytáblás kiadás.',sourceIds:['src-titan-book-prava']}
 ,{editionId:'edition-book-prava-blizzard-en-2024',workId:'work-book-prava',publisher:'Blizzard Entertainment',publicationDate:'2024-11-19',language:'en',isbn:'9781956916522',format:'hardcover',pageCount:160,editionStatement:'Blizzard Entertainment amerikai angol keménytáblás kiadás.',sourceIds:['src-target-book-prava-us']}
 ,{editionId:'edition-bul-kathos-blizzard-en-2023',workId:'work-legends-bul-kathos',publisher:'Blizzard Entertainment',publicationDate:'2023-07-11',language:'en',isbn:'9781950366965',format:'hardcover',pageCount:80,editionStatement:'Blizzard Entertainment amerikai angol keménytáblás kiadás.',sourceIds:['src-target-bul-kathos-us']}
 ,{editionId:'edition-rathma-blizzard-en-2024',workId:'work-legends-rathma',publisher:'Blizzard Entertainment',publicationDate:'2024-07-16',language:'en',isbn:'9781956916270',format:'hardcover',pageCount:80,editionStatement:'Blizzard Entertainment amerikai angol keménytáblás kiadás.',sourceIds:['src-target-rathma-us']}
];

export const seriesRegistry=[{seriesId:'series-sin-war',title:'The Sin War',workIds:['work-sin-war-birthright','work-sin-war-scales-serpent','work-sin-war-veiled-prophet'],status:'complete-audit' as const},{seriesId:'series-dawn-hatred',title:'Diablo: Dawn of Hatred',workIds:['work-dawn-hatred-1','work-dawn-hatred-2','work-dawn-hatred-3','work-dawn-hatred-4'],status:'complete-audit' as const},{seriesId:'series-sword-justice',title:'Diablo: Sword of Justice',workIds:['work-sword-justice-1','work-sword-justice-2','work-sword-justice-3','work-sword-justice-4','work-sword-justice-5'],status:'complete-audit' as const},{seriesId:'series-diablo-legends',title:'Diablo Legends',workIds:['work-legends-bul-kathos','work-legends-rathma'],status:'complete-audit' as const}];
export const verifiedClaims:VerifiedClaim[]=[
 {claimId:'claim-lost-horadrim-prequel',subjectId:'work-lost-horadrim',predicate:'precedes',value:'Diablo IV: Lord of Hatred',sourceIds:['src-prh-lost-horadrim'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A hivatalos kiadói rekord közvetlenül Lord of Hatred-előzményregényként azonosítja.'},
 {claimId:'claim-lost-horadrim-skovo-alliance',subjectId:'work-lost-horadrim',predicate:'centralConflict',value:'Lorath és Adreona szövetsége a Skovos-szigeteken',sourceIds:['src-prh-lost-horadrim'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A hivatalos kiadói összefoglaló nevezi meg a két szereplőt, a helyszínt és a központi konfliktust.'},
 {claimId:'claim-eternal-conflict-before-sanctuary',subjectId:'eternal-conflict',predicate:'precedes',value:'Sanctuary megteremtése',sourceIds:['src-blizzard-tyrael-spotlight'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard hivatalos Tyrael-összefoglalója az Örök Konfliktust Sanctuary és az emberiség létrejötte elé helyezi.'},
 {claimId:'claim-worldstone-eternal-conflict',subjectId:'worldstone',predicate:'contestedDuring',value:'Eternal Conflict',sourceIds:['src-blizzard-malthael-nexus'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard hivatalos Malthael-összefoglalója szerint a Worldstone többször gazdát cserélt az Örök Konfliktus során.'},
 {claimId:'claim-tyrael-destroyed-worldstone',subjectId:'tyrael',predicate:'destroyed',value:'Worldstone',sourceIds:['src-blizzard-tyrael-spotlight','src-blizzard-malthael-nexus'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Két hivatalos Blizzard-karakterösszefoglaló azonos állítása.'},
 {claimId:'claim-malthael-abandoned-angiris',subjectId:'malthael',predicate:'abandoned',value:'Angiris Council',sourceIds:['src-blizzard-malthael-nexus'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-karakterösszefoglaló.'},
 {claimId:'claim-malthael-destroy-sanctuary',subjectId:'malthael',predicate:'intendedDestructionOf',value:'Sanctuary és lakói',sourceIds:['src-blizzard-malthael-nexus'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-karakterösszefoglaló; nem vezet be forrás nélküli pontos dátumot.'},
 {claimId:'claim-immortal-between',subjectId:'diablo-immortal',predicate:'chronologicalPlacement',value:'Diablo II: Lord of Destruction után és Diablo III előtt',sourceIds:['src-blizzard-immortal-story-so-far'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-állítás.'},
 {claimId:'claim-immortal-five-years',subjectId:'diablo-immortal',predicate:'startsAfter',value:'Öt évvel a Worldstone pusztulása után',sourceIds:['src-blizzard-immortal-overview'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-állítás.'},
 {claimId:'claim-d4-fifty-years',subjectId:'diablo-4',predicate:'startsAfter',value:'Ötven évvel a Diablo III eseményei után',sourceIds:['src-blizzard-d4-new-saga'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Blizzard fejlesztői történeti összefoglaló.'},
 {claimId:'claim-d4-power-vacuum',subjectId:'diablo-4',predicate:'historicalContext',value:'A Black Soulstone pusztulása, Malthael bukása és a súlyos népességveszteség után kialakuló hatalmi vákuumban tér vissza Lilith',sourceIds:['src-blizzard-d4-unveiled'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-történeti összefoglaló.'},
 {claimId:'claim-zakarum-crusader-origin',subjectId:'zakarum',predicate:'historicalDevelopment',value:'Akarat tanításaiból nőtt ki; Mephisto korrupciója miatt Akkhan létrehozta a Zakarum megtisztítását kereső keresztes rendet',sourceIds:['src-blizzard-crusade-history'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard hivatalos Crusader-történeti közleménye.'},
 {claimId:'claim-voh-continuation',subjectId:'vessel-of-hatred',predicate:'continues',value:'A Neyrelle és Mephisto körüli Diablo IV-történetet folytatja Nahantuban',sourceIds:['src-blizzard-voh'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Hivatalos kiegészítőoldal.'},
 {claimId:'claim-reckoning-no-story',subjectId:'season-of-reckoning',predicate:'hasSeparateStory',value:'false',sourceIds:['src-blizzard-reckoning'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard kifejezetten kizárja a külön szezonális történetet.'}
 ,{claimId:'claim-tales-four-stories',subjectId:'work-tales-of-sanctuary',predicate:'hasParts',value:'Witness; The Toll of Darkness and Light; Sanctum of Bone; Teeth of the Plague',sourceIds:['src-blizzard-tales-1-2','src-blizzard-sanctum-bone','src-blizzard-teeth-plague'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A négy hivatalos Blizzard-történetoldal közvetlenül azonosítja a gyűjtemény részeit.'}
 ,{claimId:'claim-all-who-lie-belial',subjectId:'belial',predicate:'returnsTo',value:'Sanctuary',sourceIds:['src-blizzard-all-who-lie'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'REVIEW_REQUIRED',reason:'A visszatérés hivatalos, de a 184 eseményes fő kronológiában pontos elhelyezés előtt szerkesztői ellenőrzést igényel.'}
 ,{claimId:'claim-nightmares-wings-parts',subjectId:'work-on-nightmares-wings',predicate:'hasParts',value:'Neyrelle; Adreona; Lorath',sourceIds:['src-blizzard-nightmares-wings'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A hivatalos Blizzard-oldal három történetet és három főszereplőt nevez meg.'}
 ,{claimId:'claim-webtoons-six-parts',subjectId:'work-webtoons-sanctuary',predicate:'hasParts',value:'Goatmen; A New Addition; The Cure; A Visit with Grandfather; Only in Darkness; Blood for the Revenant',sourceIds:['src-blizzard-webtoons-sanctuary'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard-oldal mind a hat epizódot felsorolja.'}
 ,{claimId:'claim-webtoons-fictional-frame',subjectId:'work-webtoons-sanctuary',predicate:'narrativeFrame',value:'Sanctuary lakói által mesélt elképzelt rémtörténetek',sourceIds:['src-blizzard-webtoons-sanctuary'],canonStatus:'CANON_PROBABLE',confidence:.95,dateStatus:'UNKNOWN',publicationRecommendation:'REVIEW_REQUIRED',reason:'A hivatalos bevezető imagined terrors megfogalmazása miatt az epizódok nem kezelhetők automatikusan történelmi eseményként.'}
 ,{claimId:'claim-warlock-vizjerei-origin',subjectId:'warlock',predicate:'historicalOrigin',value:'A tiltott démonidézést gyakorló Vizjerei hagyományából ered',sourceIds:['src-blizzard-warlock-lore'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'Közvetlen Blizzard-osztálytörténet.'}
 ,{claimId:'claim-neyrelle-death',subjectId:'neyrelle',predicate:'lifeStatus',value:'deceased',sourceIds:['src-blizzard-light-extinguished'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'REVIEW_REQUIRED',reason:'Közvetlen Blizzard-közlemény, de súlyos Lord of Hatred-spoiler; publikálása spoilerkaput igényel.'}
 ,{claimId:'claim-dawn-hatred-placement',subjectId:'work-dawn-hatred-series',predicate:'chronologicalPlacement',value:'A Diablo IV és a Vessel of Hatred eseményei után',sourceIds:['src-titan-dawn-hatred','src-prh-dawn-hatred-collection'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A két kiadói leírás egymástól függetlenül ugyanazt a relatív elhelyezést adja.'}
 ,{claimId:'claim-dawn-hatred-parts',subjectId:'work-dawn-hatred-series',predicate:'hasParts',value:'Dawn of Hatred #1; #2; #3; #4',sourceIds:['src-titan-dawn-hatred'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'EXACT',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Titan hivatalos sorozatoldala mind a négy füzetet és dátumukat felsorolja.'}
 ,{claimId:'claim-diablo-archive-parts',subjectId:'work-diablo-archive',predicate:'hasParts',value:'Legacy of Blood; The Black Road; The Kingdom of Shadow; Demonsbane',sourceIds:['src-worldcat-diablo-archive'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A könyvtári rekord mind a négy gyűjteményi részt azonosítja.'}
 ,{claimId:'claim-demonsbane-blackmarch',subjectId:'work-demonsbane',predicate:'storySetting',value:'A blackmarchi mészárlás következményei',sourceIds:['src-google-demonsbane','src-worldcat-diablo-archive'],canonStatus:'CANON_PROBABLE',confidence:.94,dateStatus:'RELATIVE',publicationRecommendation:'REVIEW_REQUIRED',reason:'Két bibliográfiai összefoglaló egyezik, de nem közvetlen játékforrás; történeti idővonalra csak külön kánonaudit után kerülhet.'}
 ,{claimId:'claim-book-tyrael-companion',subjectId:'work-book-of-tyrael',predicate:'companionTo',value:'Diablo III: Book of Cain',sourceIds:['src-google-book-tyrael','src-simon-diablo-series'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A bibliográfiai és kiadói rekord egyaránt társkiadványként azonosítja.'}
 ,{claimId:'claim-horadric-library-parts',subjectId:'work-horadric-library',predicate:'hasVerifiedParts',value:'The Gospel of Death; The Rose of Khanduras; A Collar of Thorns; A Whiff of Salt; The Tomb of Tal Rasha; When the Dark Seeps In; Beyond That Door There Lies No Light',sourceIds:['src-cadl-horadric-library'],canonStatus:'CANON_CONFIRMED',confidence:.98,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A könyvtári tartalomjegyzék cím és szerző szerint azonosítja a hét történetet.'}
 ,{claimId:'claim-heroes-rise-parts',subjectId:'work-heroes-rise',predicate:'hasParts',value:'Hatred and Discipline; Wayfarer; Unyielding; Firefly; Doubtwalker; Theatre Macabre: The Dark Exile; The Hunger',sourceIds:['src-blizzard-heroes-rise-announcement','src-google-heroes-rise'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard közleménye hét történetet rögzít, a bibliográfiai tartalomjegyzék pedig cím és szerző szerint azonosítja őket.'}
 ,{claimId:'claim-tales-sanctuary-comic-parts',subjectId:'work-tales-sanctuary-comic',predicate:'hasParts',value:"Rage; The Hand of Naz; Hatred's Bride",sourceIds:['src-blizzard-arreat-tales-sanctuary','src-gcd-tales-sanctuary'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'UNKNOWN',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard háromrészes műként írja le, a képregény-bibliográfia pedig megnevezi mindhárom történetet.'}
 ,{claimId:'claim-morbed-setting',subjectId:'work-morbed',predicate:'storySetting',value:'Egy távoli sziget, ahová ellopott westmarchi tárgyak nyomai vezetnek',sourceIds:['src-simon-morbed'],canonStatus:'CANON_PROBABLE',confidence:.96,dateStatus:'UNKNOWN',publicationRecommendation:'REVIEW_REQUIRED',reason:'Hivatalos kiadói összefoglaló igazolja a helyszínt, de a fő kronológiában nincs primary-source dátum.'}
 ,{claimId:'claim-sword-justice-parts',subjectId:'work-sword-justice-series',predicate:'hasParts',value:'Diablo #1; Diablo #2; Diablo #3; Diablo #4; Diablo #5',sourceIds:['src-dc-sword-justice','src-dc-diablo-1','src-dc-diablo-2','src-dc-diablo-3','src-dc-diablo-4','src-dc-diablo-5'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'EXACT',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A DC kiadói sorozat- és füzetoldalai az öt részt és megjelenési sorrendjüket közvetlenül igazolják.'}
 ,{claimId:'claim-bul-kathos-children',subjectId:'bul-kathos',predicate:'parentOf',value:'Naarah és Hiram',sourceIds:['src-titan-bul-kathos'],canonStatus:'CANON_PROBABLE',confidence:.98,dateStatus:'MYTHIC',publicationRecommendation:'REVIEW_REQUIRED',reason:'A hivatalos kiadói összefoglaló nevezi meg az ikergyermekeket; a történet mitikus korszakának pontos időpontja nem ismert.'}
 ,{claimId:'claim-rathma-linarian',subjectId:'rathma',predicate:'formerName',value:'Linarian',sourceIds:['src-titan-rathma'],canonStatus:'CANON_PROBABLE',confidence:.97,dateStatus:'RELATIVE',publicationRecommendation:'REVIEW_REQUIRED',reason:'A kiadói cím Rathmaként, a leírás Linarian néven azonosítja a főszereplőt; fő idővonalas publikálás előtt elsődleges játékszöveges ellenőrzés szükséges.'}
 ,{claimId:'claim-shadows-sanctuary-parts',subjectId:'work-shadows-sanctuary',predicate:'hasProbableParts',value:'Witness; The Toll of Darkness and Light; Sanctum of Bone; Teeth of the Plague; Instincts; We Are All Guilty',sourceIds:['src-titan-shadows-sanctuary','src-simon-au-shadows-sanctuary','src-blizzard-tales-1-2','src-blizzard-sanctum-bone','src-blizzard-teeth-plague','src-blizzard-instincts','src-blizzard-we-are-all-guilty'],canonStatus:'CANON_PROBABLE',confidence:.92,dateStatus:'UNKNOWN',publicationRecommendation:'REVIEW_REQUIRED',reason:'A kiadói szerzőlista és a hat hivatalos digitális történet szerzői egyeznek, de közvetlen kiadói tartalomjegyzék nem volt elérhető; ezért a tagság nem automatikusan publikálható.'}
 ,{claimId:'claim-instincts-blood-knight',subjectId:'work-instincts',predicate:'classContext',value:'Blood Knight',sourceIds:['src-blizzard-instincts'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard közvetlenül a Blood Knight hivatalos bemutatójában publikálta és nevezte meg a történetet.'}
 ,{claimId:'claim-guilty-tempest',subjectId:'work-we-are-all-guilty',predicate:'classContext',value:'Tempest',sourceIds:['src-blizzard-we-are-all-guilty'],canonStatus:'CANON_CONFIRMED',confidence:.99,dateStatus:'RELATIVE',publicationRecommendation:'AUTO_PUBLISH_CANDIDATE',reason:'A Blizzard közvetlenül a Tempest hivatalos bemutatójában publikálta és nevezte meg a történetet.'}
 ,{claimId:'claim-book-prava-placement',subjectId:'work-book-prava',predicate:'chronologicalPlacement',value:'A Cathedral of Light Burning Hellsben elszenvedett veresége után',sourceIds:['src-titan-book-prava','src-target-book-prava-us'],canonStatus:'CANON_PROBABLE',confidence:.97,dateStatus:'RELATIVE',publicationRecommendation:'REVIEW_REQUIRED',reason:'Két kiadói/bibliográfiai leírás egyezik, de a fő idővonal pontos pontja előtt játékforrásos ellenőrzés szükséges.'}
];

export const rejectedSourceLog=[{category:'pirated-full-text',reason:'Jogosulatlan teljes könyv vagy ismeretlen PDF-tükör; kutatási és publikációs forrásként elutasítva.'},{category:'fan-wiki-without-primary-citation',reason:'Csak kutatási nyom, bizonyítékként elutasítva.'}];
export const missingSourceList=['A 184 idővonalesemény teljes, egyenkénti primary-source auditja','A Horadric Library kiadásai közötti tartalomjegyzék- és oldalszámeltérés feloldása','A Diablo I és Diablo II kézikönyvek kiadástörténeti metaadatainak további ellenőrzése','A Shadows of Sanctuary közvetlen kiadói tartalomjegyzékének ellenőrzése','A Bul-Kathos és Rathma Panini és további lokalizált kiadásainak ellenőrzése','Magyar és további lokalizált kiadások Edition-szintű ellenőrzése'];

export function validateResearchRegistries(){
 const sourceIds=new Set(sourceRegistry.map(s=>s.sourceId));const workIds=new Set(creativeWorkRegistry.map(w=>w.workId));const editionIds=new Set(editionRegistry.map(e=>e.editionId));const seriesIds=new Set(seriesRegistry.map(s=>s.seriesId));const claimIds=new Set(verifiedClaims.map(c=>c.claimId));const issues:string[]=[];
 if(sourceIds.size!==sourceRegistry.length)issues.push('DUPLICATE_SOURCE_ID');if(workIds.size!==creativeWorkRegistry.length)issues.push('DUPLICATE_WORK_ID');if(editionIds.size!==editionRegistry.length)issues.push('DUPLICATE_EDITION_ID');if(seriesIds.size!==seriesRegistry.length)issues.push('DUPLICATE_SERIES_ID');if(claimIds.size!==verifiedClaims.length)issues.push('DUPLICATE_CLAIM_ID');
 const urls=new Set<string>();for(const s of sourceRegistry){if(!/^https:\/\//.test(s.canonicalUrl)||!/^[a-f0-9]{64}$/.test(s.fingerprint))issues.push(`INVALID_SOURCE:${s.sourceId}`);if(urls.has(s.canonicalUrl))issues.push(`DUPLICATE_SOURCE_URL:${s.sourceId}`);urls.add(s.canonicalUrl);}
 for(const w of creativeWorkRegistry){if(w.sourceIds.length===0||w.sourceIds.some(id=>!sourceIds.has(id)))issues.push(`BROKEN_WORK_SOURCE:${w.workId}`);if(w.relatedWorks.some(id=>!workIds.has(id)||id===w.workId))issues.push(`BROKEN_RELATED_WORK:${w.workId}`);if(w.isPartOf&&!workIds.has(w.isPartOf))issues.push(`BROKEN_PARENT:${w.workId}`);if(w.isPartOf===w.workId)issues.push(`SELF_PARENT:${w.workId}`);if(w.seriesId&&!seriesIds.has(w.seriesId))issues.push(`BROKEN_WORK_SERIES:${w.workId}`);const visited=new Set<string>();let cursor=w;while(cursor.isPartOf){if(visited.has(cursor.workId)){issues.push(`PARENT_CYCLE:${w.workId}`);break;}visited.add(cursor.workId);const parent=creativeWorkRegistry.find(item=>item.workId===cursor.isPartOf);if(!parent)break;cursor=parent;}}
 for(const series of seriesRegistry){if(new Set(series.workIds).size!==series.workIds.length||series.workIds.some(id=>!workIds.has(id)))issues.push(`BROKEN_SERIES:${series.seriesId}`);const orders=series.workIds.map(id=>creativeWorkRegistry.find(w=>w.workId===id)?.seriesOrder);if(orders.some((order,index)=>order!==index+1))issues.push(`BROKEN_SERIES_ORDER:${series.seriesId}`);}
 for(const e of editionRegistry){if(!workIds.has(e.workId)||e.sourceIds.length===0||e.sourceIds.some(id=>!sourceIds.has(id)))issues.push(`BROKEN_EDITION:${e.editionId}`);}for(const c of verifiedClaims){if(c.sourceIds.length===0||c.sourceIds.some(id=>!sourceIds.has(id))||c.confidence<0||c.confidence>1)issues.push(`CLAIM_WITHOUT_PROVENANCE:${c.claimId}`);}return issues;
}
