export interface KnowledgeProfile { entityId: string; universeId: string; type: string; factPredicates: string[]; relationshipTypes: string[]; evidenceCount: number; citationCompleteness: number; qualityScore: number }
export interface KnowledgeGap { id: string; universeId: string; entityId: string; kind: 'missing-fact' | 'missing-relationship' | 'missing-evidence' | 'low-quality'; field: string; severity: number; reason: string }
export interface ResearchRecommendation { gapId: string; query: string; preferredSourceKinds: string[]; priority: number; requiresHumanApproval: true }
export interface IntelligenceClaim { id: string; universeId: string; subjectId: string; predicate: string; objectKey: string; polarity: 'affirmative' | 'negative'; confidence: number; evidenceIds: string[] }
export class KnowledgeIntelligence {
  detectGaps(profiles: KnowledgeProfile[], required: Record<string, { facts: string[]; relationships: string[] }>): KnowledgeGap[] { const result: KnowledgeGap[] = []; for (const profile of profiles) { const rules = required[profile.type] ?? { facts: [], relationships: [] }; for (const field of rules.facts.filter((field) => !profile.factPredicates.includes(field))) result.push(this.#gap(profile, 'missing-fact', field, 80, `Missing required fact: ${field}`)); for (const field of rules.relationships.filter((field) => !profile.relationshipTypes.includes(field))) result.push(this.#gap(profile, 'missing-relationship', field, 70, `Missing relationship: ${field}`)); if (!profile.evidenceCount || profile.citationCompleteness < 1) result.push(this.#gap(profile, 'missing-evidence', 'evidence', 90, 'Evidence or citations incomplete')); if (profile.qualityScore < 70) result.push(this.#gap(profile, 'low-quality', 'quality', 100 - profile.qualityScore, `Quality score ${profile.qualityScore}`)); } return result.sort((a, b) => b.severity - a.severity || a.id.localeCompare(b.id)); }
  recommend(gaps: KnowledgeGap[]): ResearchRecommendation[] { return gaps.map((gap) => ({ gapId: gap.id, query: `${gap.entityId} ${gap.field} authoritative source`, preferredSourceKinds: gap.kind === 'missing-evidence' ? ['primary', 'official'] : ['primary', 'secondary'], priority: gap.severity, requiresHumanApproval: true as const })).sort((a, b) => b.priority - a.priority); }
  contradictions(claims: IntelligenceClaim[]): Array<{ leftId: string; rightId: string; type: 'object' | 'polarity'; severity: number }> { const result: Array<{ leftId: string; rightId: string; type: 'object' | 'polarity'; severity: number }> = []; for (let left = 0; left < claims.length; left++) for (let right = left + 1; right < claims.length; right++) { const a = claims[left], b = claims[right]; if (a.universeId !== b.universeId || a.subjectId !== b.subjectId || a.predicate !== b.predicate) continue; const type = a.polarity !== b.polarity ? 'polarity' : a.objectKey !== b.objectKey ? 'object' : null; if (type) result.push({ leftId: a.id, rightId: b.id, type, severity: Math.round(Math.min(a.confidence, b.confidence) * 100) }); } return result; }
  selfAudit(universeId: string, profiles: KnowledgeProfile[], claims: IntelligenceClaim[], required: Record<string, { facts: string[]; relationships: string[] }>) { const scopedProfiles = profiles.filter((item) => item.universeId === universeId); const scopedClaims = claims.filter((item) => item.universeId === universeId); const gaps = this.detectGaps(scopedProfiles, required); const contradictions = this.contradictions(scopedClaims); const averageQuality = scopedProfiles.length ? scopedProfiles.reduce((sum, item) => sum + item.qualityScore, 0) / scopedProfiles.length : 0; return { universeId, entities: scopedProfiles.length, claims: scopedClaims.length, gaps, contradictions, averageQuality, healthy: gaps.every((gap) => gap.severity < 70) && contradictions.length === 0 && averageQuality >= 80 }; }
  autonomousResearchLoop(report: ReturnType<KnowledgeIntelligence['selfAudit']>, maximumRecommendations = 20): ResearchRecommendation[] { if (maximumRecommendations < 1 || maximumRecommendations > 100) throw new Error('Research loop limit invalid'); return this.recommend(report.gaps).slice(0, maximumRecommendations); }
  #gap(profile: KnowledgeProfile, kind: KnowledgeGap['kind'], field: string, severity: number, reason: string): KnowledgeGap { return { id: `gap:${profile.universeId}:${profile.entityId}:${kind}:${field}`, universeId: profile.universeId, entityId: profile.entityId, kind, field, severity, reason }; }
}
