export interface WikiEntity { id: string; universeId: string; type: string; title: string; description: string; aliases: string[]; imageUrl?: string }
export interface WikiFact { id: string; entityId: string; label: string; value: string; confidence: number; canonStatus: string; evidenceIds: string[] }
export interface WikiRelation { id: string; fromId: string; toId: string; type: string; label: string; confidence: number }
export interface WikiEvent { id: string; title: string; timeLabel: string; earliest: number | null; latest: number | null; participantIds: string[]; evidenceIds: string[] }
export interface WikiEvidence { id: string; sourceTitle: string; locator: string; quote: string; reliability: number }
export interface WikiPageModel { entity: WikiEntity; facts: WikiFact[]; sources: WikiEvidence[]; relationships: Array<WikiRelation & { counterpart: WikiEntity }>; timeline: WikiEvent[]; graph: { nodes: Array<{ id: string; label: string; type: string }>; edges: Array<{ id: string; from: string; to: string; label: string }> } }
export interface WikiRepository { entity(id: string): Promise<WikiEntity | null>; facts(entityId: string): Promise<WikiFact[]>; relations(entityId: string): Promise<WikiRelation[]>; events(entityId: string): Promise<WikiEvent[]>; evidence(ids: string[]): Promise<WikiEvidence[]> }
export interface WikiSearchProvider { search(input: { universeId: string; query: string; locale: string; intelligent: boolean; limit: number }): Promise<Array<{ entity: WikiEntity; score: number; explanation: string[] }>> }
export class WikiEngine {
  readonly repository: WikiRepository; readonly searchProvider: WikiSearchProvider;
  constructor(repository: WikiRepository, searchProvider: WikiSearchProvider) { this.repository = repository; this.searchProvider = searchProvider; }
  async page(universeId: string, entityId: string): Promise<WikiPageModel> { const entity = await this.repository.entity(entityId); if (!entity || entity.universeId !== universeId) throw new Error('Wiki entity not found in universe'); const [facts, relations, events] = await Promise.all([this.repository.facts(entityId), this.repository.relations(entityId), this.repository.events(entityId)]); const relatedIds = [...new Set(relations.map((relation) => relation.fromId === entityId ? relation.toId : relation.fromId))]; const related = new Map<string, WikiEntity>(); for (const id of relatedIds) { const item = await this.repository.entity(id); if (item?.universeId === universeId) related.set(id, item); }
    const validRelations = relations.filter((relation) => related.has(relation.fromId === entityId ? relation.toId : relation.fromId)); const evidenceIds = [...new Set([...facts.flatMap((fact) => fact.evidenceIds), ...events.flatMap((event) => event.evidenceIds)])]; const sources = await this.repository.evidence(evidenceIds); const relationships = validRelations.map((relation) => ({ ...relation, counterpart: related.get(relation.fromId === entityId ? relation.toId : relation.fromId)! }));
    return { entity, facts: facts.sort((a, b) => b.confidence - a.confidence || a.id.localeCompare(b.id)), sources: sources.sort((a, b) => b.reliability - a.reliability || a.id.localeCompare(b.id)), relationships, timeline: events.sort((a, b) => (a.earliest ?? Infinity) - (b.earliest ?? Infinity) || a.id.localeCompare(b.id)), graph: { nodes: [{ id: entity.id, label: entity.title, type: entity.type }, ...[...related.values()].map((item) => ({ id: item.id, label: item.title, type: item.type }))], edges: validRelations.map((relation) => ({ id: relation.id, from: relation.fromId, to: relation.toId, label: relation.label })) } };
  }
  async search(universeId: string, query: string, options: { locale?: string; intelligent?: boolean; limit?: number } = {}) { if (!query.trim()) return []; const limit = options.limit ?? 20; if (limit < 1 || limit > 100) throw new Error('Wiki search limit must be between 1 and 100'); const results = await this.searchProvider.search({ universeId, query, locale: options.locale ?? 'hu', intelligent: options.intelligent ?? true, limit }); return results.filter((item) => item.entity.universeId === universeId).sort((a, b) => b.score - a.score || a.entity.id.localeCompare(b.entity.id)).slice(0, limit); }
}
