import{LitElement,html,css}from'lit';import{customElement,state}from'lit/decorators.js';import{creativeWorkRegistry,editionRegistry,missingSourceList,sourceRegistry,verifiedClaims}from'../research/registry.ts';
@customElement('source-library')export class SourceLibrary extends LitElement{
 @state()private query='';@state()private view:'sources'|'works'|'claims'='sources';
 static styles=css`:host{display:block;width:100%;max-width:1100px;color:#eaddc5}.toolbar,.card{background:#151011;border:1px solid #d4af3744;border-radius:1rem;padding:1rem}.toolbar{position:sticky;top:0;z-index:5}.tabs{display:flex;flex-wrap:wrap;gap:.5rem}.tabs button{min-height:44px;border:1px solid #d4af3766;background:#211718;color:#eaddc5;border-radius:.5rem;padding:.6rem 1rem}.tabs button[aria-pressed=true]{color:#d4af37;border-color:#d4af37}.search{box-sizing:border-box;width:100%;margin-top:.8rem;background:#090707;border:1px solid #d4af3755;color:#fff;padding:.8rem;border-radius:.5rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:1rem;margin-top:1rem}.card h2{color:#d4af37;font-size:1.1rem}.meta{font-size:.84rem;color:#c9bda8}.badge{display:inline-block;border:1px solid #d4af3755;border-radius:2rem;padding:.2rem .5rem;margin:.15rem}.card a{color:#e6c65c;overflow-wrap:anywhere}.warning{border-color:#c9832c;color:#ffd18a}ul{padding-left:1.2rem}@media(max-width:600px){.toolbar{position:static}}`;
 private match(...values:unknown[]){return values.join(' ').toLocaleLowerCase('hu').includes(this.query.trim().toLocaleLowerCase('hu'));}
 render(){return html`<section aria-labelledby="sources-title"><h1 id="sources-title">Forrástár és műjegyzék</h1><p>Ellenőrzött provenance-rekordok. A rendszer nem tárol kalóz teljes szöveget, és a hiányzó bizonyítékot nem jelöli kánonnak.</p><div class="toolbar"><div class="tabs" role="group" aria-label="Forrástár nézet"><button aria-pressed=${this.view==='sources'} @click=${()=>this.view='sources'}>Források (${sourceRegistry.length})</button><button aria-pressed=${this.view==='works'} @click=${()=>this.view='works'}>Művek (${creativeWorkRegistry.length})</button><button aria-pressed=${this.view==='claims'} @click=${()=>this.view='claims'}>Ellenőrzött állítások (${verifiedClaims.length})</button></div><label><span class="sr-only">Keresés a forrástárban</span><input class="search" type="search" placeholder="Forrás, mű vagy állítás keresése…" .value=${this.query} @input=${(e:InputEvent)=>this.query=(e.target as HTMLInputElement).value}></label></div>
 ${this.view==='sources'?html`<div class="grid">${sourceRegistry.filter(s=>this.match(s.title,s.game,s.expansion,s.notes)).map(s=>html`<article class="card"><h2>${s.title}</h2><div><span class="badge">${s.sourcePriority}</span><span class="badge">${s.officialStatus}</span><span class="badge">${s.sourceType}</span></div><p>${s.notes}</p><p class="meta">Kiadó: ${s.publisher} · hozzáférés: ${s.accessDate}${s.isbn?` · ISBN ${s.isbn}`:''}</p><a href=${s.canonicalUrl} target="_blank" rel="noopener noreferrer">Eredeti forrás megnyitása ↗</a></article>`)}</div>`:''}
 ${this.view==='works'?html`<div class="grid">${creativeWorkRegistry.filter(w=>this.match(w.title,w.originalTitle,w.authors,w.description)).map(w=>{const editions=editionRegistry.filter(e=>e.workId===w.workId);const parent=w.isPartOf?creativeWorkRegistry.find(item=>item.workId===w.isPartOf):undefined;return html`<article class="card"><h2>${w.title}</h2><div><span class="badge">${w.type}</span><span class="badge">${w.canonStatus}</span></div><p>${w.description}</p><p class="meta">Szerző: ${w.authors.join(', ')}${w.seriesOrder?` · sorozat ${w.seriesOrder}. része`:''}${parent?` · gyűjtemény: ${parent.title}`:''}</p><p class="meta">${editions.length} ellenőrzött kiadás${editions.map(e=>e.isbn?` · ISBN ${e.isbn}`:'').join('')}</p></article>`;})}</div>`:''}
 ${this.view==='claims'?html`<div class="grid">${verifiedClaims.filter(c=>this.match(c.subjectId,c.predicate,c.value,c.reason)).map(c=>html`<article class="card"><h2>${c.subjectId}: ${c.predicate}</h2><p>${c.value}</p><div><span class="badge">${c.canonStatus}</span><span class="badge">${Math.round(c.confidence*100)}%</span><span class="badge">${c.dateStatus}</span></div><p class="meta">${c.reason}</p></article>`)}</div>`:''}
 <aside class="card warning" aria-labelledby="missing-sources"><h2 id="missing-sources">Dokumentált kutatási hiányok</h2><ul>${missingSourceList.map(item=>html`<li>${item}</li>`)}</ul></aside></section>`;}
}
