export type ReviewStatus = 'pending' | 'in-review' | 'approved' | 'rejected';
export interface ReviewItem<T = unknown> { id: string; universeId: string; kind: string; payload: T; origin: 'human' | 'ai' | 'import'; status: ReviewStatus; priority: number; assignedTo: string | null; version: number; createdAtUtc: string; updatedAtUtc: string }
export interface ReviewChange { id: string; itemId: string; universeId: string; action: 'submitted' | 'claimed' | 'modified' | 'approved' | 'rejected'; actorId: string; actorType: 'human' | 'system'; fromVersion: number; toVersion: number; reason: string; timestampUtc: string }
export class EditorialWorkflow {
  #items = new Map<string, ReviewItem>(); #history: ReviewChange[] = [];
  submit<T>(item: ReviewItem<T>, actorId = 'system'): void { if (this.#items.has(item.id) || item.status !== 'pending' || item.version !== 1 || item.priority < 0 || item.priority > 100) throw new Error('Invalid review submission'); this.#items.set(item.id, structuredClone(item)); this.#record(item, 'submitted', actorId, 'system', 1, 1, 'submitted'); }
  queue(universeId: string, options: { status?: ReviewStatus; assignedTo?: string; limit?: number } = {}): ReviewItem[] { const limit = options.limit ?? 100; if (limit < 1 || limit > 500) throw new Error('Queue limit invalid'); return [...this.#items.values()].filter((item) => item.universeId === universeId && (!options.status || item.status === options.status) && (!options.assignedTo || item.assignedTo === options.assignedTo)).sort((a, b) => b.priority - a.priority || a.createdAtUtc.localeCompare(b.createdAtUtc) || a.id.localeCompare(b.id)).slice(0, limit).map((item) => structuredClone(item)); }
  claim(id: string, reviewerId: string, expectedVersion: number): ReviewItem { const item = this.#get(id, expectedVersion); if (item.status !== 'pending' || !reviewerId) throw new Error('Item cannot be claimed'); const from = item.version; item.status = 'in-review'; item.assignedTo = reviewerId; item.version++; item.updatedAtUtc = new Date().toISOString(); this.#record(item, 'claimed', reviewerId, 'human', from, item.version, 'claimed'); return structuredClone(item); }
  modify<T>(id: string, reviewerId: string, expectedVersion: number, payload: T, reason: string): ReviewItem<T> { const item = this.#owned(id, reviewerId, expectedVersion); if (!reason.trim()) throw new Error('Modification reason required'); const from = item.version; item.payload = structuredClone(payload); item.version++; item.updatedAtUtc = new Date().toISOString(); this.#record(item, 'modified', reviewerId, 'human', from, item.version, reason); return structuredClone(item) as ReviewItem<T>; }
  decide(id: string, reviewerId: string, expectedVersion: number, decision: 'approved' | 'rejected', reason: string): ReviewItem { const item = this.#owned(id, reviewerId, expectedVersion); if (!reason.trim()) throw new Error('Decision reason required'); const from = item.version; item.status = decision; item.version++; item.updatedAtUtc = new Date().toISOString(); this.#record(item, decision, reviewerId, 'human', from, item.version, reason); return structuredClone(item); }
  history(itemId: string): ReviewChange[] { return this.#history.filter((item) => item.itemId === itemId).map((item) => structuredClone(item)); }
  dashboard(universeId: string) { const items = [...this.#items.values()].filter((item) => item.universeId === universeId); return { total: items.length, pending: items.filter((item) => item.status === 'pending').length, inReview: items.filter((item) => item.status === 'in-review').length, approved: items.filter((item) => item.status === 'approved').length, rejected: items.filter((item) => item.status === 'rejected').length, aiAwaitingHuman: items.filter((item) => item.origin === 'ai' && ['pending', 'in-review'].includes(item.status)).length, highPriority: items.filter((item) => item.priority >= 80 && !['approved', 'rejected'].includes(item.status)).length } as const; }
  #get(id: string, version: number): ReviewItem { const item = this.#items.get(id); if (!item) throw new Error('Review item missing'); if (item.version !== version) throw new Error('Optimistic concurrency conflict'); return item; }
  #owned(id: string, reviewerId: string, version: number): ReviewItem { const item = this.#get(id, version); if (item.status !== 'in-review' || item.assignedTo !== reviewerId) throw new Error('Review item is not owned by reviewer'); return item; }
  #record(item: ReviewItem, action: ReviewChange['action'], actorId: string, actorType: ReviewChange['actorType'], fromVersion: number, toVersion: number, reason: string): void { this.#history.push({ id: `review-change:${crypto.randomUUID()}`, itemId: item.id, universeId: item.universeId, action, actorId, actorType, fromVersion, toVersion, reason, timestampUtc: new Date().toISOString() }); }
}
