import type { LlmProvider } from '../core/llm.ts';
export interface MapLocation { id: string; universeId: string; name: string; x: number; y: number; parentId: string | null; entityIds: string[]; eventIds: string[] }
export interface ExplorerCharacter { id: string; universeId: string; name: string; type: string; relationshipIds: string[]; eventIds: string[]; factIds: string[] }
export interface StoryArc { id: string; universeId: string; title: string; eventIds: string[]; characterIds: string[]; start: number | null; end: number | null; branchId: string }
export interface VisualUnderstanding { id: string; universeId: string; mediaId: string; kind: 'map' | 'image'; labels: Array<{ text: string; confidence: number; x: number; y: number }>; entityCandidates: Array<{ label: string; entityId: string | null; confidence: number }>; model: string; status: 'staged' }
export class UniverseExplorer {
  #locations = new Map<string, MapLocation>(); #characters = new Map<string, ExplorerCharacter>(); #stories = new Map<string, StoryArc>();
  addLocations(items: MapLocation[]): void { for (const item of items) { if (this.#locations.has(item.id) || item.x < 0 || item.x > 1 || item.y < 0 || item.y > 1) throw new Error('Invalid or duplicate map location'); if (item.parentId && !this.#locations.has(item.parentId)) throw new Error('Map parent missing'); this.#locations.set(item.id, structuredClone(item)); } }
  addCharacter(item: ExplorerCharacter): void { if (this.#characters.has(item.id)) throw new Error('Duplicate character'); this.#characters.set(item.id, structuredClone(item)); }
  addStory(item: StoryArc): void { if (this.#stories.has(item.id) || item.start !== null && item.end !== null && item.start > item.end) throw new Error('Invalid or duplicate story'); this.#stories.set(item.id, structuredClone(item)); }
  map(universeId: string) { const nodes = [...this.#locations.values()].filter((item) => item.universeId === universeId); return { nodes: structuredClone(nodes), edges: nodes.filter((item) => item.parentId).map((item) => ({ from: item.parentId!, to: item.id })) }; }
  character(universeId: string, id: string) { const item = this.#characters.get(id); if (!item || item.universeId !== universeId) return null; return { ...structuredClone(item), stories: [...this.#stories.values()].filter((story) => story.universeId === universeId && story.characterIds.includes(id)).sort((a, b) => (a.start ?? Infinity) - (b.start ?? Infinity)) }; }
  stories(universeId: string, branchId?: string) { return [...this.#stories.values()].filter((item) => item.universeId === universeId && (!branchId || item.branchId === branchId)).sort((a, b) => (a.start ?? Infinity) - (b.start ?? Infinity) || a.id.localeCompare(b.id)).map((item) => structuredClone(item)); }
}
export class VisualUnderstandingService {
  readonly provider: LlmProvider; constructor(provider: LlmProvider) { if (!provider.capabilities.has('vision') || !provider.capabilities.has('structured-output')) throw new Error('Vision and structured output capabilities required'); this.provider = provider; }
  async analyze(input: { universeId: string; mediaId: string; kind: 'map' | 'image'; allowedEntityIds: string[]; imageReference: string }): Promise<VisualUnderstanding> { const response = await this.provider.generate({ temperature: 0, messages: [{ role: 'system', content: 'Analyze the referenced visual. Return labels and entity candidates only. Never create entity IDs.' }, { role: 'user', content: JSON.stringify(input) }], responseSchema: { type: 'object', required: ['labels', 'entityCandidates'] } }); const output: any = response.structuredOutput ?? JSON.parse(response.content); if (!Array.isArray(output.labels) || !Array.isArray(output.entityCandidates)) throw new Error('Invalid visual understanding output'); const allowed = new Set(input.allowedEntityIds); const labels = output.labels.map((item: any) => { if (typeof item.text !== 'string' || ![item.confidence, item.x, item.y].every((value) => typeof value === 'number' && value >= 0 && value <= 1)) throw new Error('Invalid visual label'); return { text: item.text, confidence: item.confidence, x: item.x, y: item.y }; }); const entityCandidates = output.entityCandidates.map((item: any) => { if (item.entityId !== null && !allowed.has(item.entityId) || typeof item.label !== 'string' || typeof item.confidence !== 'number' || item.confidence < 0 || item.confidence > 1) throw new Error('Invalid visual entity candidate'); return { label: item.label, entityId: item.entityId, confidence: item.confidence }; }); return { id: `visual:${response.requestId ?? crypto.randomUUID()}`, universeId: input.universeId, mediaId: input.mediaId, kind: input.kind, labels, entityCandidates, model: response.model, status: 'staged' }; }
}
