export interface ManagedUniverse { id: string; slug: string; name: string; defaultLocale: string; supportedLocales: string[]; status: 'draft' | 'active' | 'archived'; namespace: string }
export interface UniversePolicy { universeId: string; canon: { defaultBranchId: string; allowAlternateBranches: boolean; requireEvidenceForCanonical: boolean }; sourceAuthority: Array<{ sourceKind: string; tier: 'primary' | 'secondary' | 'licensed' | 'community'; priority: number }> }
export class UniverseManager { #universes = new Map<string, ManagedUniverse>(); #slugs = new Map<string, string>(); #policies = new Map<string, UniversePolicy>();
  create(universe: ManagedUniverse, policy: UniversePolicy): void { if (this.#universes.has(universe.id) || this.#slugs.has(universe.slug) || policy.universeId !== universe.id || !/^[a-z][a-z0-9-]{2,63}$/.test(universe.slug) || !/^[a-z][a-z0-9._-]{2,63}$/.test(universe.namespace)) throw new Error('Invalid or duplicate universe'); if (!universe.supportedLocales.includes(universe.defaultLocale)) throw new Error('Default locale must be supported'); if (policy.sourceAuthority.some((rule) => rule.priority < 0 || rule.priority > 100)) throw new Error('Source authority priority invalid'); this.#universes.set(universe.id, structuredClone(universe)); this.#slugs.set(universe.slug, universe.id); this.#policies.set(universe.id, structuredClone(policy)); }
  get(id: string): ManagedUniverse | null { const value = this.#universes.get(id); return value ? structuredClone(value) : null; }
  policy(id: string): UniversePolicy { const value = this.#policies.get(id); if (!value) throw new Error('Universe policy missing'); return structuredClone(value); }
  scopedId(universeId: string, localId: string): string { const universe = this.#universes.get(universeId); if (!universe || !localId || localId.includes('::')) throw new Error('Invalid scoped identity'); return `${universe.namespace}::${localId}`; }
  assertScope(universeId: string, scopedId: string): void { const universe = this.#universes.get(universeId); if (!universe || !scopedId.startsWith(`${universe.namespace}::`)) throw new Error('Cross-universe access denied'); }
  list(status?: ManagedUniverse['status']): ManagedUniverse[] { return [...this.#universes.values()].filter((item) => !status || item.status === status).sort((a, b) => a.name.localeCompare(b.name)).map((item) => structuredClone(item)); }
}
